passes around lists of project ids rather than project names
biocore/microsetta-private-api pull request #268
Opened 2020-10-15 18:05 UTC by AmandaBirmingham

2020-10-15 18:33 UTC, AmandaBirmingham commented
@wasade @dhakim87 Can you stomach a -0.06% change in test coverage?  If so, the rest of this build passes ... :)

2020-10-21 20:38 UTC, wasade commented
Not a problem :) I'm going to defer merge though until a release is demarked which I'm working on right now

2020-10-23 21:55 UTC, wasade requested changes
Just a small request, thanks!!

2020-10-23 21:55 UTC, wasade commented on microsetta_private_api/repo/admin_repo.py
> +                curr_tmi = bool(known_projects[input_proj_id])
Would it be possible to do the cast to `bool` within the dict comprehension on line 670?

2020-10-27 16:57 UTC, merged