Account Summaries Backend
biocore/microsetta-private-api pull request #277
Opened 2020-11-13 23:24 UTC by dhakim87

Supports displaying summaries of samples in accounts by email address for microsetta-admin

2020-11-13 23:49 UTC, wasade requested changes
Would it be possible to add in a test of one or two "email addresses" from the test database, with and without a project restriction?

2020-11-13 23:49 UTC, wasade commented on microsetta_private_api/admin/admin_impl.py
> +    email_list = body.get("emails")
I think this should default to `[]` rather than `None` as it is iterated over on line 320

2020-11-13 23:49 UTC, wasade commented on microsetta_private_api/repo/sample_repo.py
> +                "SELECT "
A barcode can have many scans, should the select be ordered so the latest is picked?

2020-11-14 00:20 UTC, dhakim87 commented on microsetta_private_api/repo/sample_repo.py
> +                "SELECT "
The WHERE searches with the scan_timestamp of the latest, our model can't determine which one is the latest if there are in fact two scans at the same time.  So I just break the tie with a limit 1.

2020-11-16 16:44 UTC, wasade commented on microsetta_private_api/repo/sample_repo.py
> +                "SELECT "
Okay, thanks!

2020-11-16 16:45 UTC, merged