Route to retrieve preparation data over api
biocore/microsetta-private-api pull request #279
Opened 2020-11-25 02:50 UTC by dhakim87

Adds functionality to retrieve preparation data

2020-11-25 18:07 UTC, wasade requested changes
I think this is perfect, other than it would be helpful to not require admin. It actually doesn't require authorization either as this is public detail. Sorry for not clarifying that item earlier

2020-11-26 00:28 UTC, dhakim87 commented
> I think this is perfect, other than it would be helpful to not require admin. It actually doesn't require authorization either as this is public detail. Sorry for not clarifying that item earlier

Possibilities I've considered: 
1.  Public like microsetta-public-api where you don't need an account?  
2.  Public like the read_kit route that gives unused samples from a kit?  As in, you can query this for any barcode so long as you have an account in our system?  
3.  Private to admin and/or person who has claimed this sample and has it associated with their account?
4.  Restricted to admin privileges?  

Right now on 4, I'll switch it to 2?

2020-11-26 01:21 UTC, wasade commented
Super helpful, thank you -- l think we should do (2) so we're consistent with private-api where there is a level of auth involved.

2020-12-02 01:13 UTC, wasade approved these changes

2020-12-09 17:21 UTC, merged