BUG fix: vioscreen URL had invalid DOB, causing 502 error on vioscreen
biocore/microsetta-private-api pull request #298
Opened 2021-02-24 19:12 UTC by razrichter

Added query to get birth year and gender by account_id and to assign proper values for building the vioscreen query.
All dates are June 30 of birth year, and defaults are 1/1/1970, Female

2021-02-24 19:19 UTC, wasade requested changes
Thanks @razrichter! A few small requests. I suspect it's failing right now due to flake8 errors on line lengths

2021-02-24 19:19 UTC, wasade commented on microsetta_private_api/repo/survey_template_repo.py
> +    def fetch_user_birth_year_gender(self, account_id):
An account may have multiple sources (e.g., a parent, a child, etc). Is it possible for this query to operate on `account_id` and `source_id`?

2021-02-24 19:19 UTC, wasade commented on microsetta_private_api/util/vioscreen.py
> +        gender_id = gender_map.get(gender.lower(), 2)  # again, default female
is `lower` needed? it should be controlled case in the database. Without it, it would remove the need for a conditional here against `None`

2021-02-24 19:52 UTC, razrichter commented on microsetta_private_api/util/vioscreen.py
> +        gender_id = gender_map.get(gender.lower(), 2)  # again, default female
Good to know! I saw that they were limited in the test db, but wasn't sure about live data. 
Done.

2021-02-24 19:56 UTC, wasade commented on microsetta_private_api/util/vioscreen.py
> +        gender_id = gender_map.get(gender.lower(), 2)  # again, default female
From production:

```sql
ag=> select distinct response from ag.ag_login_surveys join ag.survey_answers using (survey_id) where survey_question_id=107;
  response
-------------
 Female
 Male
 Other
 Unspecified
(4 rows)
```

2021-02-24 20:39 UTC, razrichter commented on microsetta_private_api/util/vioscreen.py
> +        gender_id = gender_map.get(gender.lower(), 2)  # again, default female
Changed as suggested.

2021-02-24 20:46 UTC, razrichter commented on microsetta_private_api/repo/survey_template_repo.py
> +    def fetch_user_birth_year_gender(self, account_id):
Could you elaborate? Are the sources such that they'd be from different people, with different sexes and birth years? A comment in read_survey_template:51-53 questions the need for source_id in the function, which is why I left it out from the query.

2021-02-24 21:25 UTC, wasade commented on microsetta_private_api/repo/survey_template_repo.py
> +    def fetch_user_birth_year_gender(self, account_id):
A source can be a human, animal or environmental, and an account can have multiple sources. If there are multiple humans, there is no assurance they are the same person. The primary surveys and samples are associated to the source directly. Does that make sense?

That TODO comment should probably be removed as it seems misleading. Want to do that in this PR?

2021-02-24 21:54 UTC, razrichter commented on microsetta_private_api/repo/survey_template_repo.py
> +    def fetch_user_birth_year_gender(self, account_id):
Got it. There may be more default/null values from the query with the added restriction (in test DB, ~2K ag_login_survey records don't have a birth year question), but considering the prior state was that all are faked, it's not likely to be a big deal.

2021-02-24 21:57 UTC, wasade commented on microsetta_private_api/repo/survey_template_repo.py
> +    def fetch_user_birth_year_gender(self, account_id):
Ya, this is going from definitely garbage to generally not garbage. It's an infinite improvement!! :)

2021-02-24 22:01 UTC, razrichter commented
I'm not sure why datetime validation tests should have failed after this change. Is there a clean way to re-run the commit hooks?

2021-02-25 00:39 UTC, dhakim87 commented on microsetta_private_api/api/_survey.py
> -
Hooray!  Someone finally used source_id for something 👍

2021-02-25 00:40 UTC, dhakim87 commented on microsetta_private_api/repo/survey_template_repo.py
> +        """Given an account ID,
and a source_id

2021-02-25 00:47 UTC, dhakim87 commented on microsetta_private_api/util/vioscreen.py
> +                ):
Looks like gender_id and dob now have matching default values in both encrypt_key and gen_survey_url.  If gen_survey_url is the only use of encrypt_key (I think it is?), can probably delete one or the other.

2021-02-25 01:03 UTC, razrichter commented on microsetta_private_api/util/vioscreen.py
> +                ):
Makes sense. Since there's no reason for encrypt_key to ever get called from more than one place, that's the one to drop the defaults.

2021-02-25 01:13 UTC, razrichter commented
I'm not sure why the tests of the swagger API are failing. I didn't touch them, and `make test` succeeds with deprecation warnings on my machine (the universal excuse...)

2021-02-25 01:33 UTC, dhakim87 commented
I actually pulled this up to check if my recent PR was failing for the same reasons.  It appears to be the same errors.  I wouldn't worry about it, I don't think it relates to this change, something must have snuck in elsewhere.

2021-02-25 01:40 UTC, wasade commented
Unclear what's causing the failure. A quick review of the commit history suggests the entity flagged as problematic was last changed 7 months ago. Agree that is should not block this PR. Smells like maybe a version issue connexion but that's just a guess right now

2021-02-25 03:29 UTC, wasade commented on microsetta_private_api/repo/survey_template_repo.py
> +        """Given an account ID,
@razrichter, I think this is the last comment then should be :+1:

2021-02-26 22:18 UTC, merged