WIP: pulling localized surveys
biocore/microsetta-private-api pull request #331
Opened 2021-05-26 15:51 UTC by wasade

This is not ready to merge yet

2021-05-28 15:49 UTC, wasade commented on microsetta_private_api/db/patches/0081.sql
> +-- spanish responses were not reflected in this table
Can merge this all into 0078

2021-05-28 15:58 UTC, wasade commented
This fixes #301, #332, #334, #335 and positions for staging deploy.

2021-05-28 19:04 UTC, wasade commented
Fixes #328

2021-05-29 00:41 UTC, wasade commented on microsetta_private_api/util/vioscreen.py
> +                    "&Height=%s"
important: need to gracefully handle missing height / weight

2021-05-29 00:42 UTC, wasade commented on microsetta_private_api/repo/survey_template_repo.py
> +                height = height[2:-2]
new survey responses _are not_ structured like this!!!

2021-06-01 20:14 UTC, dhakim87 requested changes
I think something went wrong with merging changes 0080.sql and 0081.sql.  We ended up with an empty script for 0080.sql and no corresponding change to migration_support.py as far as I can tell.  Unclear to me why that set of changes was added into 0081.sql instead.  

I suspect there's also a minor issue with height/weight parsing if the user enters gibberish when we then try to pass off to vioscreen.

2021-06-01 20:14 UTC, dhakim87 commented on microsetta_private_api/db/patches/0080.sql
> +SELECT 1;
This looks like a badly merged conflict on who gets 0080.sql.  I don't think you intended to remove the change that adds language to account table here.  Probably need to renumber the sql scripts?

2021-06-01 20:14 UTC, dhakim87 commented on microsetta_private_api/db/patches/0081.sql
> +ALTER TABLE account ALTER COLUMN preferred_language SET NOT NULL;
Running this sql is going to be weird in my local database at least, since I already applied a patch 0080 that does this.  Are we sure staging and production aren't going to run into issues here?

2021-06-01 20:14 UTC, dhakim87 commented on microsetta_private_api/db/patches/0081.sql
> +UPDATE ag.survey_response SET spanish = 'Sex Wax',     french = 'Sex Wax',     chinese = 'Sex Wax' WHERE american = 'Sex Wax';
This seems an unlikely translation

2021-06-01 20:14 UTC, dhakim87 commented on microsetta_private_api/repo/survey_template_repo.py
> +        return (birth_year, gender, height, weight)
I suspect this explodes if a user enters alkjsdglahdsglkasdg as their height or weight.  Ideally it would explode earlier, but I don't know that the input is checked before it is saved to the DB.

2021-06-01 20:14 UTC, dhakim87 commented on microsetta_private_api/db/patches/0080.sql
> +SELECT 1;
At the very least this should be matched with an entry in migration_support.py for a python update script.  An empty 0080 doesn't make any sense.

2021-06-01 20:25 UTC, wasade commented on microsetta_private_api/db/patches/0080.sql
> +SELECT 1;
0080 is i18n specific but the PR containing it was against master not the i18n branch. So things are a little weird here. It may be easiest to resolve when i18n is merged into master

2021-06-01 20:27 UTC, wasade commented on microsetta_private_api/db/patches/0081.sql
> +ALTER TABLE account ALTER COLUMN preferred_language SET NOT NULL;
0080 was merged into the wrong branch unfortunately. Staging doesn't matter as we can blow it away, however the presence of 0080 in master did create unexpected issues with the staging database

2021-06-01 20:27 UTC, wasade commented on microsetta_private_api/repo/survey_template_repo.py
> +        return (birth_year, gender, height, weight)
They "cant" as those are checked to be integer, but the null case creates problems

2021-06-01 20:28 UTC, wasade commented
> I think something went wrong with merging changes 0080.sql and 0081.sql. We ended up with an empty script for 0080.sql and no corresponding change to migration_support.py as far as I can tell. Unclear to me why that set of changes was added into 0081.sql instead.

Ish. 0080.sql is already used in master which is creating problems 

> I suspect there's also a minor issue with height/weight parsing if the user enters gibberish when we then try to pass off to vioscreen.

Issue is on nulls but yes, there is a problem

2021-06-01 20:29 UTC, wasade commented on microsetta_private_api/db/patches/0081.sql
> +UPDATE ag.survey_response SET spanish = 'Sex Wax',     french = 'Sex Wax',     chinese = 'Sex Wax' WHERE american = 'Sex Wax';
Nope, it's correct. There is a surfer questionnaire

2021-06-01 22:38 UTC, wasade commented on microsetta_private_api/repo/survey_template_repo.py
> +            localization.EN_US: "american",
...use `survey_response.`

2021-06-01 23:02 UTC, wasade commented on microsetta_private_api/repo/survey_template_repo.py
> +                height = height[2:-2]
Created an issue for this

2021-06-01 23:02 UTC, wasade commented on microsetta_private_api/repo/survey_template_repo.py
> +        return (birth_year, gender, height, weight)
Resolved when constructing the vioscreen URL for handoff

2021-06-02 21:00 UTC, dhakim87 approved these changes

2021-06-02 21:01 UTC, merged