Address Verification via Melissa
biocore/microsetta-private-api pull request #364
Opened 2021-08-10 21:08 UTC by cassidysymons

Added functionality to verify addresses using Melissa's global address API

2021-08-15 20:53 UTC, AmandaBirmingham requested changes
Requests for a few small tweaks. Looks good!

2021-08-15 20:53 UTC, AmandaBirmingham commented on microsetta_private_api/api/microsetta_private_api.yaml
> +      summary: Verify a postal address
I think this is a little unclear to a user not immersed in the address verification process.  "Verify" what?  Perhaps "Verify the correctness of a postal address" or "Verify that a postal address really exists" or "Verify that postal address is in the required format for FedEx" or ...?  (I don't know which it is :)

2021-08-15 20:53 UTC, AmandaBirmingham commented on microsetta_private_api/api/microsetta_private_api.yaml
> +          name: state
What should be passed in if the country in question does not have states/provinces and/or doesn't include them in their mailing addresses?

2021-08-15 20:53 UTC, AmandaBirmingham commented on microsetta_private_api/repo/melissa_repo.py
> +        address_2 - Secondary street address
Some indication/example of what goes in the primary and in the secondary would be a nice-to-have.  As a potential user, I'd also love some guidance on which of these fields is required (e.g., can I have an address_2 without an address_1?) and what to pass in for the ones that are optional (presumably state and postal code, as those aren't universally used ... is address_2 also optional?)

2021-08-15 20:53 UTC, AmandaBirmingham commented on microsetta_private_api/db/patches/0084.sql
> +id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
The general convention in this db is to include the name of the table in the primary key column of a table; this is useful because otherwise we end up with every table having a column named "id" and it becomes hard to keep them straight :). Therefore, I suggest this column be renamed to "melissa_address_query_id" or "address_query_id" or something ...

2021-08-15 20:53 UTC, AmandaBirmingham commented on microsetta_private_api/repo/melissa_repo.py
> +        postal - Postal code
I see state is not input here; can you add a code comment on why not?

2021-08-15 20:53 UTC, AmandaBirmingham commented on microsetta_private_api/repo/melissa_repo.py
> +            row = cur.fetchone()
Hmm, now I think I'm confused ... contrary to what the docstring states, this doesn't look like it returns a boolean in the case where a duplicate record does exist.  It is probably undesirable to have the code return a boolean (False) if a duplicate doesn't exist but to return a row if a duplicate does exist;  I suggest changing it to return None if there is no duplicate and row(s) if there is/are duplicates. 
 I say row(s) because I see no clear reason why we can assume there will only be ONE record that matches the select ... can you speak to that?

2021-08-15 20:53 UTC, AmandaBirmingham commented on microsetta_private_api/repo/melissa_repo.py
> +        formatted_address - The fully formatted address returned from API
Why do we store the formatted_address as well as storing each piece of the formatted address individually?

2021-08-15 20:53 UTC, AmandaBirmingham commented on microsetta_private_api/server_config.json
> +  "melissa_url": "http://address.melissadata.net/v3/WEB/GlobalAddress/doglobaladdress",
Is this url public info?  If not, we would want to replace it in this json with a made up one as for daklapack_api_base_url ...

2021-08-15 20:53 UTC, AmandaBirmingham commented on microsetta_private_api/util/melissa.py
> +                raise Exception("Error connecting to address verification API")
As discussed in Zoom, would be nice to have the error here include more info, such as the response.status_code and possibly its text.  Also would be nice to make the exception type more specific.

2021-08-15 20:53 UTC, AmandaBirmingham commented on microsetta_private_api/util/melissa.py
> +                record_obj = response_obj["Records"][0]
Without knowing anything about the Melissa api, I feel a bit worried about taking just the first item in a list object with a plural name ("Records").  Can you add a code comment to reassure the user about why we only ever want the first one?

2021-08-15 20:53 UTC, AmandaBirmingham commented on microsetta_private_api/util/melissa.py
> +                        r_good = True
This is probably a short list so not a big deal but: once you get to `r_good = True`, you can `break` out of the codes loop as if one code is good there's no need to examine the remaining codes.

2021-08-15 20:53 UTC, AmandaBirmingham commented on microsetta_private_api/util/melissa.py
> +                melissa_repo.update_results(record_id, url, response_raw,
If I'm reading the code right, `update_results` returns a boolean indicating whether a record was really updated, but that boolean isn't being captured/examined here.  I think it should be because if `update_results` returns false, that means that the info we think is being recorded actually isn't and that is a pathological case ... either the record_id is bogus or someone deleted a record from a table that isn't supposed to be deleted from or something is being input in a wrong format or ... whatever the reason, I think we would need to know about it and raise an exception.

2021-08-17 18:34 UTC, cassidysymons commented on microsetta_private_api/server_config.json
> +  "melissa_url": "http://address.melissadata.net/v3/WEB/GlobalAddress/doglobaladdress",
Yes, the URL is public information so there's no concern about having it visible in the code.

2021-08-17 19:00 UTC, cassidysymons commented on microsetta_private_api/api/microsetta_private_api.yaml
> +          name: state
Good catch, and this has an impact well beyond the scope of the address verification. At the moment, the state field in the database is being used as a sort of catch-all for whatever geographic unit fits between city and postal code - for the US and MX, it's state, while for GB it's storing the county in that field. As we grow into other countries, that's likely to lead to problems. Going to raise this as an issue on Slack to discuss on the AGP API call, as it's an issue that needs to be decided so we can adjust our approach for data collection (signup forms), data verification (this particular code), data storage (database), and third-party usage (e.g. shipping with Daklapak).

2021-08-24 21:07 UTC, cassidysymons commented on microsetta_private_api/api/microsetta_private_api.yaml
> +      summary: Verify a postal address
Clarified the intent of the function in the most recent commit.

2021-08-24 21:08 UTC, cassidysymons commented on microsetta_private_api/api/microsetta_private_api.yaml
> +          name: state
I added a 'required' flag to each parameter, which fits the needs of the function based on the countries within our current scope of use.

2021-08-24 21:08 UTC, cassidysymons commented on microsetta_private_api/repo/melissa_repo.py
> +        address_2 - Secondary street address
Added clarifying information to the parameters.

2021-08-24 21:09 UTC, cassidysymons commented on microsetta_private_api/db/patches/0084.sql
> +id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
I renamed the id field to a more unique and descriptive name. I also added indices to the table for the check_duplicates function.

2021-08-24 21:09 UTC, cassidysymons commented on microsetta_private_api/repo/melissa_repo.py
> +        postal - Postal code
Added comment in code explaining which fields are necessary and which are superfluous for the sake of duplicate checks.

2021-08-24 21:10 UTC, cassidysymons commented on microsetta_private_api/repo/melissa_repo.py
> +            row = cur.fetchone()
I had changed the code after I wrote the docstring. That has been updated to reflect what the function actually returns.

2021-08-24 21:12 UTC, cassidysymons commented on microsetta_private_api/repo/melissa_repo.py
> +        formatted_address - The fully formatted address returned from API
I added a comment in the code addressing this, but essentially, ease of use for potential future implementations. I'm not opposed to removing it, but my view is that database space on this scale (text strings for thousands of records) is relatively cheap and it allows us more flexibility in how we use the address verification and correction functionality.

2021-08-24 21:12 UTC, cassidysymons commented on microsetta_private_api/util/melissa.py
> +                raise Exception("Error connecting to address verification API")
I expanded the exception messages and, in the case of the potential for an HTTP failure, added response code and text.

2021-08-24 21:12 UTC, cassidysymons commented on microsetta_private_api/util/melissa.py
> +                record_obj = response_obj["Records"][0]
Added comment to code explaining that decision.

2021-08-24 21:12 UTC, cassidysymons commented on microsetta_private_api/util/melissa.py
> +                        r_good = True
Good call, and done.

2021-08-24 21:13 UTC, cassidysymons commented on microsetta_private_api/util/melissa.py
> +                melissa_repo.update_results(record_id, url, response_raw,
Good call, I missed that. Added a check for whether it succeeded and the code now raises an exception if it failed to update.

2021-08-31 22:41 UTC, closed without merging