EBI Accession urls returned in sample model objects
biocore/microsetta-private-api pull request #380
Opened 2021-09-17 19:34 UTC by dhakim87

Samples now report ebi accession url info.

2021-09-17 20:20 UTC, wasade commented on microsetta_private_api/api/_sample.py
> +    except Exception as e:
It would be pleasant to error gracefully for not found (see https://github.com/qiita-spots/qiita_client/blob/0e04e78578c8924f65e12ef6813ebadd2886c5e9/qiita_client/qiita_client.py#L310-L311)

2021-09-17 20:20 UTC, wasade commented on microsetta_private_api/api/_sample.py
> +        print("Failed to communicate with qiita", e)
This message won't make it into any logs

2021-09-17 20:20 UTC, wasade commented on microsetta_private_api/api/_sample.py
> +    qclient = QiitaClient(
Construction establishes a session, should we instead have a single instance (e.g, `from microsetta_private_api.something import qclient`) and construct this object only a single time? See https://github.com/qiita-spots/qiita_client/blob/0e04e78578c8924f65e12ef6813ebadd2886c5e9/qiita_client/qiita_client.py#L171

2021-09-17 21:05 UTC, dhakim87 commented on microsetta_private_api/api/_sample.py
> +    qclient = QiitaClient(
Done

2021-09-17 21:19 UTC, dhakim87 commented on microsetta_private_api/api/_sample.py
> +        print("Failed to communicate with qiita", e)
Hmm... ideally we would just log a message about qiita being down and not show any accession urls.  Do you want QiitaClient's NotFoundError, BadRequestError, or ForbiddenError's to bubble up to the user?  Is there a way to write BadRequest or Forbidden to the log since neither of these should be happening?

2021-09-17 22:05 UTC, wasade commented on microsetta_private_api/api/_sample.py
> +        print("Failed to communicate with qiita", e)
not found would make sense to boil up as it means the sample sequecne data isn't available in qiita. bad request, forbidden and runtime errors are problems we need to know about but the user does not

I'm also not sure what the best way to this detail into these into the logs would be, would it be possible to track that down? it might be as simple as "from flask import logger" etc

2021-09-20 21:20 UTC, wasade commented
Note test failures seem real

2021-11-18 16:51 UTC, wasade commented
yay! reviewing

2021-11-18 16:55 UTC, wasade requested changes
ive got the changes staged, will commit via gh

2021-11-18 16:55 UTC, wasade commented on microsetta_private_api/api/_sample.py
> +        print("Couldn't communicate with qiita", e)
```suggestion
```

2021-11-18 16:55 UTC, wasade commented on microsetta_private_api/api/_sample.py
> +        print("Couldn't communicate with qiita", e)
```suggestion

```

2021-11-18 16:55 UTC, wasade commented on microsetta_private_api/api/_sample.py
> +        print("Failed to communicate with qiita", e)
```suggestion

```

2021-11-18 16:55 UTC, wasade commented on microsetta_private_api/api/tests/test_api.py
> +            # This is a bit moronic, but since qiita won't be available
i'll keep this in the interest of getting this merged, but in the future we should consider `unittest.skipIf` so we can provide real credentials when needed

2021-11-18 16:56 UTC, wasade approved these changes

2021-11-18 17:04 UTC, wasade commented on microsetta_private_api/api/_sample.py
> +    except RuntimeError as e:
```suggestion
    except BadRequestError:
        # How do I log these to gunicorn??
        app.logger.warning("Couldn't communicate with qiita", exc_info=True)
    except ForbiddenError:
        # How do I log these to gunicorn??
        app.logger.warning("Couldn't communicate with qiita", exc_info=True)
    except RuntimeError:
```

2021-11-18 21:14 UTC, merged