Private API functionality for interested users.
biocore/microsetta-private-api pull request #404
Opened 2021-11-23 19:47 UTC by cassidysymons

2021-11-23 23:25 UTC, wasade requested changes
Thanks @cassidysymons

Can unit tests be added to exercise / verify behavior on the repo object? It would be good to include a test for attempting to verify an interested user that has already been verified and assert behavior is as expected. 

Integration tests against the exposed routes would be valuable as well

2021-11-23 23:25 UTC, wasade commented on microsetta_private_api/repo/interested_user_repo.py
> +                melissa_response = verify_address(r['address_1'],
This issues a remote resource call, and should be wrapped in a try/except. It would be beneficial to do this outside of the transaction context to avoid holding the transaction open unnecessarily

2021-11-23 23:25 UTC, wasade commented on microsetta_private_api/repo/interested_user_repo.py
> +    def insert_interested_user(self, **kwargs):
why not pass in an instance of `InterestedUser`?

2021-11-30 19:59 UTC, cassidysymons commented on microsetta_private_api/repo/interested_user_repo.py
> +                melissa_response = verify_address(r['address_1'],
I'm adding a try/except block but I'm unsure how to entirely move it out of the transaction context since it's a database operation. There are other remote resource calls that leave a transaction open in a similar fashion (e.g. Daklapack) and it seems inherently necessary. Can you expand on what you were thinking?

2021-11-30 20:06 UTC, wasade commented on microsetta_private_api/repo/interested_user_repo.py
> +                melissa_response = verify_address(r['address_1'],
Oh I see, you're right -- I didn't expect the db operation outside of `MelissaRepo`. Makes sense to leave as is

2021-11-30 22:05 UTC, cassidysymons commented on microsetta_private_api/repo/interested_user_repo.py
> +    def insert_interested_user(self, **kwargs):
It seemed more flexible to use the kwargs approach since interested users could end up coming from a variety of different avenues (submission form, Fundrazr, others TBD). I'm open to changing it to an instance of the InterestedUser model if you feel that's better, though.

2021-12-01 00:39 UTC, cassidysymons commented
In regards to a unit test to validate the behavior when attempting to verify an already-verified address - Melissa has no concept of a testing mode, all requests must utilize real data and a valid license key. The ramifications of this are two-fold:
1) Unit testing for the Melissa repo/functionality mostly needs to be mocked up, rather than being able to test the remote resource.
2) Anything that interacts with Melissa - for example, interested_users - can then interact with the mock process.

If we want to proceed that way, I can set up the mock testing for Melissa, then link interested user testing in to that.

2021-12-03 23:59 UTC, wasade commented
Sorry for the delay, just saw the comment. Why not `patch` the `verify_address` method? https://github.com/biocore/microsetta-private-api/pull/404/files#diff-8f4fe0085812e80c6dca2c22037d070c32252604607e2117afe53d9a25cbdb45R77 We might be saying the same thing though

2021-12-04 00:03 UTC, wasade commented on microsetta_private_api/repo/interested_user_repo.py
> +    def insert_interested_user(self, **kwargs):
Thanks! For other repos with complex arguments, we have been utilizing model objects (eg vioscreen). A benefit here is future modification to the model doesn't change the public method signature

2021-12-07 21:06 UTC, wasade requested changes

2021-12-07 21:06 UTC, wasade commented on microsetta_private_api/repo/tests/test_interested_user_repo.py
> +
Could a test for `test_verify_address_not_previously_verified_isvalid` and `test_verify_address_not_previously_verified_isinvalid` which mocks out `microsetta_private_api.util.melissa.verify_address` using a `unittest.patch` be added so that we can cover the remaining logic of the `InterestedUserRepo.verify_address` method?

2021-12-07 21:06 UTC, wasade commented on microsetta_private_api/repo/tests/test_interested_user_repo.py
> +            t.rollback()
```suggestion
```

A rollback is implicit; commit needs to be explicit

2021-12-07 21:47 UTC, cassidysymons commented on microsetta_private_api/model/interested_user.py
> +    def from_dict(cls, values_dict):
Different models in the existing code base handle it differently - e.g. project.py is similar to what I wrote while others enumerate the parameters in the constructor similar to your example. Would you prefer to use the latter going forward?

2021-12-07 22:06 UTC, wasade commented on microsetta_private_api/model/interested_user.py
> +    def from_dict(cls, values_dict):
fair, good point, precedence ftw, let's leave as is

2021-12-08 19:10 UTC, wasade commented on microsetta_private_api/repo/tests/test_interested_user_repo.py
> +
It looks like there are mocks on `microsetta_private_api.repo.interested_user_repo.verify_address` rather than `microsetta_private_api.util.melissa.verify_address`. Doing the mocking at the lower level will ensure the database operations within `microsetta_private_api.repo.interested_user_repo.verify_address` are exercised

2021-12-13 17:15 UTC, cassidysymons commented on microsetta_private_api/repo/tests/test_interested_user_repo.py
> +
I just dove into this and as far as I can tell, the way I have it patched is exercising the database operations in `microsetta_private_api.repo.interested_user_repo.verify_address`. I added a `t.commit()` to `test_verify_address_not_verified_is_valid` and the latitude, longitude, address_checked, and address_valid fields all update as intended in the `interested_users` table.

When I change the patch to `microsetta_private_api.util.melissa.verify_address`, it attempts to connect to the Melissa API (and fails, as expected, since the license key is removed). Am I misunderstanding what you were requesting or is the mocking working as intended?

2021-12-13 17:19 UTC, wasade commented on microsetta_private_api/repo/tests/test_interested_user_repo.py
> +
I think I see that now, thanks

2021-12-13 17:20 UTC, wasade commented
I'm :+1: following a `mv` on `0090.sql` to a new patch number

2021-12-13 21:08 UTC, wasade commented
The failure is unrelated, and weird. I'm merging and will investigate the CI issue after

2021-12-13 21:08 UTC, merged