Fixed Duplicate Source Name and Email Check
biocore/microsetta-private-api pull request #445
Opened 2022-08-01 21:51 UTC by Ram6911

2022-08-02 22:19 UTC, Ram6911 commented on microsetta_private_api/repo/source_repo.py
> +                        "source.participant_email = %s AND "
Instead of AND we should use OR

2022-08-02 23:16 UTC, Ram6911 commented on microsetta_private_api/api/_source.py
> +            source["message"] = DUPLICATE_SOURCE_AND_EMAIL
Change DUPLICATE_SOURCE_AND_EMAIL to TRUE

2022-08-02 23:23 UTC, Ram6911 commented on microsetta_private_api/repo/source_repo.py
> +                        "source.participant_email = %s AND "
Done

2022-08-02 23:23 UTC, Ram6911 commented on microsetta_private_api/api/_source.py
> +            source["message"] = DUPLICATE_SOURCE_AND_EMAIL
Done

2022-08-03 16:00 UTC, cassidysymons requested changes

2022-08-03 16:00 UTC, cassidysymons commented on microsetta_private_api/api/_source.py
> +            source["message"] = TRUE
Please change the return value to an actual boolean (true/false). The goal is to return a boolean, rather than a string, so that if we need to change the message that's displayed, we can do it at the Interface level rather than the API level.

2022-08-03 16:00 UTC, cassidysymons commented on microsetta_private_api/api/literals.py
> +TRUE = "It looks like you're creating a new source " \
This literal can be removed.

2022-08-03 16:00 UTC, cassidysymons commented on microsetta_private_api/api/microsetta_private_api.yaml
> +  '/accounts/{account_id}/source_email_match':
Please change this to '/accounts/{account_id}/check_duplicate_source' - we want the name to be as clear and descriptive as possible.

2022-08-03 16:00 UTC, cassidysymons commented on microsetta_private_api/repo/source_repo.py
> +                        "source.source_name = %s",
This query isn't achieving what we're looking for. When you're using both AND and OR statements in a conditional, you need to use parentheses to meet the condition. We're looking for any source that matches account_id AND (participant email OR source_name).

2022-08-03 16:00 UTC, cassidysymons commented on microsetta_private_api/api/microsetta_private_api.yaml
> +          $ref: '#/components/responses/404NotFound'
Can this function actually return all of these HTTP codes?

2022-08-17 16:31 UTC, cassidysymons requested changes

2022-08-17 16:31 UTC, cassidysymons commented on microsetta_private_api/api/_source.py
> +def check_duplicate_source_name_email(account_id, body):
Can you add _validate_account_access() to this function please?

2022-08-24 22:00 UTC, cassidysymons approved these changes

2022-08-24 22:00 UTC, merged