Request account removal
biocore/microsetta-private-api pull request #447
Opened 2022-08-02 17:26 UTC by charles-cowart

API support for an account removal queue.

2022-08-02 22:30 UTC, charles-cowart commented on microsetta_private_api/api/microsetta_private_api.yaml
> +  '/admin/requests/account_removal/list':
remove 'requests' from this endpoint

2022-08-02 22:31 UTC, charles-cowart commented on microsetta_private_api/api/tests/test_api.py
> +        self.assertEqual(200, response.status_code)
confirm?

2022-08-02 22:32 UTC, charles-cowart commented on microsetta_private_api/api/tests/test_api.py
> +        self.assertEqual(200, response.status_code)
Add a comment block to describe the logic block (it is not in the block is returned below).

2022-08-02 22:46 UTC, charles-cowart commented on microsetta_private_api/repo/account_repo.py
> +                if not admin_id:
remove this

2022-08-02 22:48 UTC, charles-cowart commented on microsetta_private_api/repo/account_repo.py
> +                cur.execute(sql)
change query format to use %s and similar vs f"{variable}".

2022-08-03 23:34 UTC, cassidysymons requested changes

2022-08-03 23:34 UTC, cassidysymons commented on microsetta_private_api/admin/admin_impl.py
> +# from microsetta_private_api.localization import EN_US
```suggestion
```

2022-08-03 23:34 UTC, cassidysymons commented on microsetta_private_api/admin/admin_impl.py
> +        #                                     EN_US])
Try changing this to the send_email function modeled after line 452 in campaign_repo.py and see if it works locally and passes CI. Also, please pulled the user's language preference out of their account and use that rather than hardcoding EN_US.

2022-08-03 23:34 UTC, cassidysymons commented on microsetta_private_api/api/_account.py
> +        return jsonify(result), 200
```suggestion

   return jsonify(result), 200
```

2022-08-03 23:34 UTC, cassidysymons commented on microsetta_private_api/api/_account.py
> +    return jsonify(code=200, message="Request Accepted"), 200
This function is defined but is never called and has no API endpoint attached. Did you mean to create an API endpoint for it or can it and its correlating function in the repo be removed?

2022-08-03 23:34 UTC, cassidysymons commented on microsetta_private_api/api/microsetta_private_api.yaml
> +  '/admin/requests/account_removal/list':
```suggestion
  '/admin/account_removal/list':
```

2022-08-03 23:34 UTC, cassidysymons commented on microsetta_private_api/api/tests/test_api.py
> +        response = self.client.get(('/api/accounts/0a2dff3c-ec0e-4d97-b469-'
Using a static account ID here seems less than ideal. Can we clean up this section of the test by dynamically creating a UUID and ensuring it doesn't exist in the ag.account table, then use that UUID for this test case?

2022-08-03 23:34 UTC, cassidysymons commented on microsetta_private_api/api/tests/test_api.py
> +        self.assertEqual(404, response.status_code)
Can you add comments for what these test cases are doing?

2022-08-03 23:34 UTC, cassidysymons commented on microsetta_private_api/repo/account_repo.py
> +            raise RepoException("Account is not in removal queue")
Can we move all of these into removal_queue_repo.py since they act on the removal queue rather than the account table?

2022-08-03 23:40 UTC, charles-cowart commented on microsetta_private_api/api/microsetta_private_api.yaml
> +  '/admin/requests/account_removal/list':
done! I'll be pushing an update to Microsetta-inteface as well for this.

2022-08-03 23:48 UTC, charles-cowart commented on microsetta_private_api/admin/admin_impl.py
> +        #                                     EN_US])
Sure thing! Just an FYI celery_send_mail is the name it's imported under in this file but it is the same function as the one in campaign_repo.py, w/out the apply_async().

2022-08-03 23:54 UTC, charles-cowart commented on microsetta_private_api/api/_account.py
> +    return jsonify(code=200, message="Request Accepted"), 200
ty for the catch! No, it is vestigial. I'll remove it.

2022-08-03 23:58 UTC, charles-cowart commented on microsetta_private_api/api/tests/test_api.py
> +        response = self.client.get(('/api/accounts/0a2dff3c-ec0e-4d97-b469-'
Sure, no problem! Although I must say it should be statistically unlikely it will ever be found in the accounts table.

2022-08-04 00:20 UTC, charles-cowart commented on microsetta_private_api/api/tests/test_api.py
> +        response = self.client.get(('/api/accounts/0a2dff3c-ec0e-4d97-b469-'
Okay, small problem. The functionality we'd use to confirm that any new UUID4 is not in the system is the same function we're testing. I'll dynamically generate a new UUID but I'll continue to rely on its statistical uniqueness.

2022-08-04 00:42 UTC, charles-cowart commented on microsetta_private_api/repo/account_repo.py
> +            raise RepoException("Account is not in removal queue")
Sure! It doesn't look like they rely on other functions in account_repo.py.

2022-08-04 02:27 UTC, charles-cowart commented on microsetta_private_api/repo/account_repo.py
> +            raise RepoException("Account is not in removal queue")
Hmm, it seems like this is more involved than I previously thought. Still working on it.

2022-08-31 21:10 UTC, charles-cowart commented on microsetta_private_api/admin/admin_impl.py
> +        #                                     EN_US])
Note: send_mail() functionality proved troublesome to implement as was removed as a requirement for this PR.

2022-08-31 21:42 UTC, charles-cowart commented
@cassidysymons Ready for review/approval/merge.

2022-10-28 19:31 UTC, wasade requested changes
The API test was pretty good, but I was surprised to not see unit tests.

2022-10-28 19:31 UTC, wasade commented on microsetta_private_api/api/_removal_queue.py
> +    # _account.py. TODO: Remove and replace
Please do this

2022-10-28 19:31 UTC, wasade commented on microsetta_private_api/api/_removal_queue.py
> +    # _account.py. TODO: Remove and replace
Please do this

2022-10-28 19:31 UTC, wasade commented on microsetta_private_api/api/_removal_queue.py
> +    # WARNING: this does NOT authenticate a user but tests for the
This sounds really important.

2022-10-28 19:31 UTC, wasade commented on microsetta_private_api/db/patches/0102.sql
> +       cause regular delete_account() calls to fail if the account_id is
Should the existing deletion method be made aware of this queue so that we can preserve the FK relationship?

2022-10-28 19:31 UTC, wasade commented on microsetta_private_api/db/patches/0102.sql
> +       cause regular delete_account() calls to fail if the account_id is
I think yes, because presumably we want that existing method to be able to INSERT into `account_removal_log`?

2022-10-28 19:31 UTC, wasade commented on microsetta_private_api/db/patches/0102.sql
> +    /* constraint on admin_id relaxed for similar reasons as above.*/
The account ID for an admin will exist though. I think a FK relationship is maintainable

2022-10-28 19:31 UTC, wasade commented on microsetta_private_api/repo/removal_queue_repo.py
> +                cur.execute("INSERT INTO delete_account_queue (account_id) "
Can an explicit test be performed so that the transaction object isn't left in a bad state?

2022-10-28 19:31 UTC, wasade commented on microsetta_private_api/repo/removal_queue_repo.py
> +                self._transaction.commit()
We commit outside of the repo objects as we cannot guarantee how the Transaction will be used

2022-10-28 19:31 UTC, wasade commented on microsetta_private_api/repo/removal_queue_repo.py
> +                    self._transaction.commit()
Same here

2022-10-28 19:31 UTC, wasade commented on microsetta_private_api/admin/admin_impl.py
> +            rq_repo.update_queue(account_id, token_info['sub'], 'ignored')
Why is the `sub` being used here? We do not guarantee that `auth_sub` is unique in the database, so this cannot be assumed to describe a unique account. Can the admin's account ID be used instead?

2022-10-28 19:31 UTC, wasade commented on microsetta_private_api/admin/admin_impl.py
> +            rq_repo.update_queue(account_id, token_info['sub'], 'deleted')
Same here

2022-10-28 19:31 UTC, wasade commented on microsetta_private_api/repo/removal_queue_repo.py
> +                admin_id = cur.fetchone()[0]
See the comment above about `auth_sub`. We should use the admin's account ID

2022-10-28 19:31 UTC, wasade commented on microsetta_private_api/repo/removal_queue_repo.py
> +                self._transaction.commit()
Same here

2022-10-28 19:31 UTC, wasade commented on microsetta_private_api/repo/removal_queue_repo.py
> +                cur.execute("DELETE FROM delete_account_queue WHERE account_id"
Maybe I missed it, but shouldn't this method call the account deletion? If it does not, we create (possible) scenario, particularly if multiple transactions are involved, where the account is migrated to the account_removal_log but not actually deleted

2022-10-28 19:31 UTC, wasade commented on microsetta_private_api/templates/email/account_deleted.jinja2
> +<html>
Is this email template ever used?

2022-12-13 18:02 UTC, charles-cowart commented on microsetta_private_api/api/_removal_queue.py
> +    # WARNING: this does NOT authenticate a user but tests for the
Resolved. This function was originally written by Olivier and it's got a specific use in _vioscreen.py. I don't use it in _removal_queue.py so I will remove it entirely.

2022-12-13 18:20 UTC, charles-cowart commented on microsetta_private_api/repo/removal_queue_repo.py
> +                cur.execute("INSERT INTO delete_account_queue (account_id) "
Will do! Resolved.

2022-12-13 18:29 UTC, charles-cowart commented on microsetta_private_api/repo/removal_queue_repo.py
> +                self._transaction.commit()
gotcha. Fixed.

2022-12-13 18:34 UTC, charles-cowart commented on microsetta_private_api/templates/email/account_deleted.jinja2
> +<html>
Nope. Resolved.

2022-12-13 19:45 UTC, charles-cowart commented on microsetta_private_api/admin/admin_impl.py
> +            rq_repo.update_queue(account_id, token_info['sub'], 'ignored')
@wasade @cassidysymons Hi guys. The issue here is the email is in the clear and the database entries are encrypted. Poking through the code I didn't find the encryption functionality used. Just so I don't spend more time looking around, what is it that we're using?

2022-12-13 19:52 UTC, wasade commented on microsetta_private_api/admin/admin_impl.py
> +            rq_repo.update_queue(account_id, token_info['sub'], 'ignored')
Neither the email nor the database are encrypted

2022-12-13 20:03 UTC, charles-cowart commented on microsetta_private_api/admin/admin_impl.py
> +            rq_repo.update_queue(account_id, token_info['sub'], 'ignored')
@wasade These look encrypted to me. These are from my local ag.accounts.email. Do I have it wrong?
bxxpcpe(ub@_pjmg.kjj
 kuzquaaksf@if_ap.1c8
 akmk96mse'@oqlgw.inx
 bvewaycpix@eypzn.9si
 3p4py4kyik@hnwwz.tnc
 36on(a)qxz@i&7h6.y9c
 h1epvndbjo@1_s84.czh
 rxmpvf33s1@do56p.c4b
 htl+60hops@k4i0f.4ur
 ee&gpn)/3y@ivp'n.iux

2022-12-13 20:07 UTC, cassidysymons commented on microsetta_private_api/admin/admin_impl.py
> +            rq_repo.update_queue(account_id, token_info['sub'], 'ignored')
They're not encrypted, test data is mangled/obfuscated to remove any PII. The production database is not encrypted.

2022-12-13 20:11 UTC, cassidysymons commented on microsetta_private_api/admin/admin_impl.py
> +            rq_repo.update_queue(account_id, token_info['sub'], 'ignored')
Verify this by creating an account (standard or admin) and searching for the email. You'll find that the email is clear text.

2022-12-13 21:01 UTC, charles-cowart commented on microsetta_private_api/admin/admin_impl.py
> +            rq_repo.update_queue(account_id, token_info['sub'], 'ignored')
Thanks @cassidysymons!

2022-12-13 21:50 UTC, charles-cowart commented on microsetta_private_api/db/patches/0102.sql
> +    /* constraint on admin_id relaxed for similar reasons as above.*/
Resolved.

2022-12-13 22:09 UTC, charles-cowart commented
make sure new repo has success and failure tests as needed.

2022-12-14 03:01 UTC, charles-cowart commented
@cassidysymons @wasade Unit tests for removal_queue_repo are in. I'm going to address the remaining issues now.

2022-12-14 03:07 UTC, charles-cowart commented on microsetta_private_api/db/patches/0102.sql
> +       cause regular delete_account() calls to fail if the account_id is
Resolved. I was able to reintroduce UNIQUE NOT NULL REFERENCES ag.account(id) on account_id and adjust the test cleanups, and whatnot to make the tests pass.

2022-12-14 03:13 UTC, charles-cowart commented on microsetta_private_api/repo/removal_queue_repo.py
> +                cur.execute("DELETE FROM delete_account_queue WHERE account_id"
This is handled in allow_removal_request():

https://github.com/charles-cowart/microsetta-private-api/blob/4b8f9455cebaf0392c6eb7645704d2b049af7276/microsetta_private_api/admin/admin_impl.py#L882-L897

2022-12-14 03:17 UTC, charles-cowart commented
@wasade @cassidysymons Tentatively done. Comments appreciated.

2022-12-15 20:08 UTC, charles-cowart commented on microsetta_private_api/api/_removal_queue.py
> +def cancel_request_remove_account(account_id, token_info):
verify this has an endpoint.

2022-12-15 20:10 UTC, charles-cowart commented on microsetta_private_api/api/tests/test_api.py
> +        # successful.
can we refine these to delete just the specific accounts rather than all of them?

2022-12-15 20:18 UTC, charles-cowart commented on microsetta_private_api/repo/tests/test_removal_queue_repo.py
> +            cur = t.cursor()
make sure these are also not blanket.

2022-12-16 02:53 UTC, charles-cowart commented on microsetta_private_api/api/_removal_queue.py
> +def cancel_request_remove_account(account_id, token_info):
Endpoint added. I apparently added cancel_request_remove_account () for completeness. The UI doesn't use this functionality because we didn't want the user to cancel a request once they made it, and do it again. The UI will instead show a 'Your account deletion request is being reviewed.' msg instead.

2022-12-16 03:23 UTC, charles-cowart commented
@cassidysymons tentatively good. Please feel free to review.

2023-01-05 20:02 UTC, cassidysymons commented on microsetta_private_api/db/patches/0110.sql
> +    disposition VARCHAR(8),
Change to ENUM

2023-01-06 22:21 UTC, merged