remove kit id and code from activation form
biocore/microsetta-private-api pull request #452
Opened 2022-08-30 19:35 UTC by raginirai553

2022-09-01 03:52 UTC, raginirai553 commented
Lint error fixed

2022-09-06 18:34 UTC, cassidysymons requested changes

2022-09-06 18:34 UTC, cassidysymons commented on microsetta_private_api/model/account.py
> +            "",
Rather than passing in a blank string here, can you update the class to remove the property completely? The relevant unit and integration tests will need to be updated as well.

2022-09-06 18:34 UTC, cassidysymons commented on microsetta_private_api/api/tests/test_api.py
> +        print(response_obj)
Please make sure to remove debug output before submitting pull requests.

2022-09-06 20:22 UTC, raginirai553 commented on microsetta_private_api/model/account.py
> +            "",
Removing the property completely means many downstream changes like in DB and most importantly in source creation, sample allocation etc. Created_with_kit_id on account DB is referenced and used further in listing and looking up samples. We probably will need to rewrite codes for source and sample creation if we wish to completely remove it. If you wish I can continue to work to achieve that

2022-09-06 20:22 UTC, raginirai553 commented on microsetta_private_api/api/tests/test_integration.py
> +                # "kit_name": "jb_qhxqe",
Will remove it soon

2022-09-06 20:22 UTC, raginirai553 commented on microsetta_private_api/api/tests/test_api.py
> +        print(response_obj)
sure, will do that

2022-09-06 20:33 UTC, raginirai553 commented on microsetta_private_api/api/tests/test_api.py
> +        print(response_obj)
done

2022-09-06 20:33 UTC, cassidysymons commented on microsetta_private_api/model/account.py
> +            "",
Please look into it and write up specifications on what all would need to be changed downstream and how long you think it would take to implement those changes.

2022-09-06 20:33 UTC, raginirai553 commented on microsetta_private_api/api/tests/test_integration.py
> +                # "kit_name": "jb_qhxqe",
done

2022-09-14 17:28 UTC, cassidysymons requested changes

2022-09-14 17:28 UTC, cassidysymons commented on microsetta_private_api/db/patches/0063.sql
> -ALTER TABLE ag.account ALTER COLUMN created_with_kit_id SET NOT NULL;
We can't change old database patches, we need to create a new database patch that makes the desired change to the existing structure.

2022-09-14 17:28 UTC, cassidysymons commented on microsetta_private_api/model/account.py
> +                 created_with_kit_id=None,
Is there any reason why you're leaving the created_with_kit_id in the Account model?

2022-09-14 18:12 UTC, raginirai553 commented on microsetta_private_api/model/account.py
> +                 created_with_kit_id=None,
the existing database has that column in the account table. Intent is to not make any changes to avoid downtime and unknown dependency issues.It is to ensure accounts created earlier continue to function as is. Removing column in table might result in downtime and functionalities of old accounts.Let me know if any concerns.

2022-09-14 18:12 UTC, raginirai553 commented on microsetta_private_api/db/patches/0063.sql
> -ALTER TABLE ag.account ALTER COLUMN created_with_kit_id SET NOT NULL;
Writing a new patch for this setting.

2022-09-14 18:17 UTC, raginirai553 commented on microsetta_private_api/model/account.py
> +                 created_with_kit_id=None,
like there is an admin action which retrieves account details based on created_with_kit_id

2022-09-15 01:00 UTC, closed without merging