final code for kit id removal from account creation process
biocore/microsetta-private-api pull request #455
Opened 2022-09-15 02:12 UTC by raginirai553

Added new patch for DB to remove not a null constraint as advised

2022-09-19 21:56 UTC, cassidysymons requested changes

2022-09-19 21:56 UTC, cassidysymons commented on microsetta_private_api/db/patches/0063.sql
> +ALTER TABLE ag.account ALTER COLUMN created_with_kit_id SET NOT NULL;
Please undo all of your changes to 0063.sql so that it's in its original state.

2022-09-19 21:56 UTC, cassidysymons commented on microsetta_private_api/db/patches/0103.sql
> +ALTER TABLE ag.account ALTER COLUMN created_with_kit_id DROP NOT NULL;
Please add a newline at the end of the file.

2022-09-20 01:30 UTC, raginirai553 commented on microsetta_private_api/db/patches/0063.sql
> +ALTER TABLE ag.account ALTER COLUMN created_with_kit_id SET NOT NULL;
0063.sql is already back to its original state. No net changes introduced to it. As advised I added a new patch file 0103.sql.

2022-09-20 01:33 UTC, raginirai553 commented on microsetta_private_api/db/patches/0103.sql
> +ALTER TABLE ag.account ALTER COLUMN created_with_kit_id DROP NOT NULL;
This is new patch file.This is not a line add to a file but brand new file. I have added a comment to make the file clearer.
Please let me know if you meant something else.

2022-09-20 01:53 UTC, cassidysymons requested changes

2022-09-20 01:53 UTC, cassidysymons commented on microsetta_private_api/db/patches/0063.sql
> +ALTER TABLE ag.account ALTER COLUMN created_with_kit_id SET NOT NULL;
It it not in its original state, GitHub is listing it as a changed file. It might just be an issue of what kind of end-of-line character appears at the end of the file, but we can't merge a pull request that includes changes to a historical database patch.

2022-09-20 01:53 UTC, cassidysymons commented on microsetta_private_api/db/patches/0103.sql
> +ALTER TABLE ag.account ALTER COLUMN created_with_kit_id DROP NOT NULL;
If you hover over the red dash in a circle, GitHub is providing a warning saying "No newline at end of file." It refers to a newline character - https://en.wikipedia.org/wiki/Newline.

2022-09-20 02:53 UTC, raginirai553 commented on microsetta_private_api/db/patches/0103.sql
> +ALTER TABLE ag.account ALTER COLUMN created_with_kit_id DROP NOT NULL;
looks like I needed to enter to add a new line in the file(EOL). I dont see the error any more in Github

2022-09-20 03:07 UTC, raginirai553 commented on microsetta_private_api/db/patches/0063.sql
> +ALTER TABLE ag.account ALTER COLUMN created_with_kit_id SET NOT NULL;
looks like I needed to enter to add a new line in the file(EOL). I don't see the no newline error any more in Github.
Also when I check the files changed in GIthub, it is no longer showing up as changed file.

2022-09-28 21:29 UTC, cassidysymons approved these changes

2022-09-28 21:30 UTC, merged