Move FFQ's from sample to source
biocore/microsetta-private-api pull request #459
Opened 2022-09-19 19:09 UTC by SyedAli-789

2022-10-14 17:47 UTC, cassidysymons requested changes

2022-10-14 17:47 UTC, cassidysymons commented on microsetta_private_api/repo/survey_template_repo.py
> +    def get_vioscreen_id_if_exists(self, account_id, source_id):
Since there used to be only one vioscreen entry per sample, it was safe to return rows[0][0]. However, there can now be multiple vioscreen sessions attached to a source. Please look at what functions call get_vioscreen_id_if_exists() and determine how the logic needs to be modified to return the most appropriate vioscreen_registry row for a given account+source.

2022-10-18 19:07 UTC, cassidysymons requested changes

2022-10-27 22:24 UTC, cassidysymons requested changes

2022-10-27 22:24 UTC, cassidysymons commented on microsetta_private_api/repo/survey_template_repo.py
>      def get_vioscreen_id_if_exists(self, account_id, source_id,
After some discussion with others, I think we want to refactor this a bit, unfortunately. There are some historical uses where we're going to want to still be able to search by sample_id, rather than relying on timestamp proximity. Additionally, we need to accommodate the fact that users will now be unlocking FFQs with a registration code. With that in mind, we want to allow for four scenarios (account_id and source_id will always be parameters):
1) sample_id, which will maintain the existing functionality of searching for a vio_id based on account_id + source_id + sample_id
2) registration_code
3) closest to a given timestamp
4) most recent

I think we can make sample_id, registration_code, and timestamp all optional parameters, and prioritize the lookup based on the order I just wrote them in. If a sample_id is provided, always use that. Then try registration_code, then try timestamp, then default to most recent.

2022-10-27 22:24 UTC, cassidysymons commented on microsetta_private_api/repo/survey_template_repo.py
> +    def create_vioscreen_id(self, account_id, source_id):
We need to adjust the logic on this function, since a given source can have more than one vioscreen ID associated. Since users will unlock access using a registration code, go ahead and add activation_code as a column to the vioscreen_registry table (column type = varchar). Then, you need to pass the registration_code into get_vioscreen_id_if_exists. If it doesn't, create the new record in vioscreen_registry, including the registration_code.

2022-10-27 22:24 UTC, cassidysymons commented on microsetta_private_api/api/_vioscreen.py
> +def _get_session_by_account_details(account_id, source_id):
Please update all of the functions in _vioscreen.py that call get_vioscreen_id_if_exists to include the new optional parameters (both in how they call that function and their own function definition) so we can update the full stack of functions to work with the intended logic. Also, please update the parameters in the YAML file accordingly.

2022-10-27 22:24 UTC, cassidysymons commented on microsetta_private_api/repo/vioscreen_repo.py
> +    def get_vioscreen_session(self, account_id, source_id):
```suggestion
    def get_vioscreen_sessions(self, account_id, source_id):
```

2022-10-27 22:24 UTC, cassidysymons commented on microsetta_private_api/repo/vioscreen_repo.py
> +    def get_vioscreen_session(self, account_id, source_id):
Making it plural to better reflect that it can return more than one record.

2022-10-27 22:24 UTC, cassidysymons commented on microsetta_private_api/api/_vioscreen.py
> +def get_vioscreens(account_id, source_id):
```suggestion
def get_vioscreen_sessions(account_id, source_id):
```

2022-10-27 22:24 UTC, cassidysymons commented on microsetta_private_api/api/microsetta_private_api.yaml
> +  '/vioscreen/{account_id}/sources/{source_id}/vioscreen':
```suggestion
  '/vioscreen/{account_id}/sources/{source_id}/vioscreen_sessions':
```

2022-10-28 16:33 UTC, wasade reviewed
Added a few comments

@cassidysymons, is there going to be a need to migrate existing data in anyway?

2022-10-28 16:33 UTC, wasade commented on microsetta_private_api/api/microsetta_private_api.yaml
> +        # - $ref: '#/components/parameters/sample_id'
Please remove the commented out lines

2022-10-28 16:33 UTC, wasade commented on microsetta_private_api/api/microsetta_private_api.yaml
> +                  object
I believe this is inaccurate, isn't the return an array of object?

2022-10-28 16:33 UTC, wasade commented on microsetta_private_api/repo/vioscreen_repo.py
> +                return rows
Can this return instances of the `VioscreenSession` model?

2022-10-28 16:37 UTC, cassidysymons commented
> Added a few comments
> 
> @cassidysymons, is there going to be a need to migrate existing data in anyway?

@wasade Not that I'm aware of. We're leaving the sample_id column in place and providing a way to search for Vioscreen sessions for historical records using that column.

2022-10-28 16:46 UTC, wasade commented
@cassidysymons, thanks. We currently pull out sample <-> vioscreen ID associations to construct FFQ metadata suitable for analysis (see #461) -- it's going to be important that that method remain correct in light of the changes here.

2022-10-28 16:46 UTC, wasade commented
Ah sorry, clicked the wrong button

2022-10-28 21:22 UTC, cassidysymons requested changes

2022-10-28 21:22 UTC, cassidysymons commented on microsetta_private_api/api/_survey.py
> +                                 language_tag, survey_redirect_url):
registration_code should be a parameter for this function, and should also be passed into create_vioscreen_id() on line 62

2022-10-28 21:22 UTC, cassidysymons commented on microsetta_private_api/api/_survey.py
> +                         language_tag, token_info, survey_redirect_url=None):
We also want to add registration_code here so it can be passed to the function that generates the Vioscreen URL.

2022-10-28 21:22 UTC, cassidysymons commented on microsetta_private_api/api/_survey.py
> +                                                   survey_redirect_url)
Add registration_code

2022-10-28 21:22 UTC, cassidysymons commented on microsetta_private_api/api/_vioscreen.py
> +def _get_session_by_account_details(account_id, source_id):
No, it should be updated to to use the switching logic between sample_id, registration_code, timestamp, or default to most recent.

2022-10-28 21:22 UTC, cassidysymons commented on microsetta_private_api/api/_vioscreen.py
> +def read_vioscreen_session(account_id, source_id, token_info):
Need to add sample_id, registration_code, and timestamp as optional parameters so they can be provided to _get_session_by_account_details()

2022-10-28 21:22 UTC, cassidysymons commented on microsetta_private_api/api/_vioscreen.py
> +def read_vioscreen_percent_energy(account_id, source_id, token_info):
Need to add sample_id, registration_code, and timestamp as optional parameters so they can be provided to _get_session_by_account_details()

2022-10-28 21:22 UTC, cassidysymons commented on microsetta_private_api/api/_vioscreen.py
> +def read_vioscreen_dietary_score(account_id, source_id, token_info):
Need to add sample_id, registration_code, and timestamp as optional parameters so they can be provided to _get_session_by_account_details()

2022-10-28 21:22 UTC, cassidysymons commented on microsetta_private_api/api/_vioscreen.py
> +def read_vioscreen_supplements(account_id, source_id, token_info):
Need to add sample_id, registration_code, and timestamp as optional parameters so they can be provided to _get_session_by_account_details()

2022-10-28 21:22 UTC, cassidysymons commented on microsetta_private_api/api/_vioscreen.py
> +def read_vioscreen_food_components(account_id, source_id, token_info):
Need to add sample_id, registration_code, and timestamp as optional parameters so they can be provided to _get_session_by_account_details()

2022-10-28 21:22 UTC, cassidysymons commented on microsetta_private_api/api/_vioscreen.py
> +def read_vioscreen_eating_patterns(account_id, source_id, token_info):
Need to add sample_id, registration_code, and timestamp as optional parameters so they can be provided to _get_session_by_account_details()

2022-10-28 21:22 UTC, cassidysymons commented on microsetta_private_api/api/_vioscreen.py
> +def read_vioscreen_mpeds(account_id, source_id, token_info):
Need to add sample_id, registration_code, and timestamp as optional parameters so they can be provided to _get_session_by_account_details()

2022-10-28 21:22 UTC, cassidysymons commented on microsetta_private_api/api/_vioscreen.py
> +def read_vioscreen_food_consumption(account_id, source_id, token_info):
Need to add sample_id, registration_code, and timestamp as optional parameters so they can be provided to _get_session_by_account_details()

2022-10-28 21:22 UTC, cassidysymons commented on microsetta_private_api/api/_vioscreen.py
> +    """Obtain a vioscreen ID if it exists"""
Yes. @SyedAli-789 please clarify the comment for this function.

2022-10-28 21:22 UTC, cassidysymons commented on microsetta_private_api/api/microsetta_private_api.yaml
> +        # - $ref: '#/components/parameters/sample_id'
Along with removing any commented lines, please make sure the YAML file reflects the new optional parameters we're adding. @SyedAli-789

2022-10-31 15:35 UTC, cassidysymons requested changes

2022-10-31 15:35 UTC, cassidysymons commented on microsetta_private_api/api/_survey.py
>  def _remote_survey_url_vioscreen(transaction, account_id, source_id,
We need this function to accept either vioscreen_ext_sample_id or registration_code. While we'll be using registration_code going forward, we can't assume that all legacy Vioscreen FFQs have been completed, so we need to support vioscreen_ext_sample_id as well. That should have a couple of changes:
1) Add both parameters to the function definition, both being optional
2) Try vioscreen_ext_sample_id first
3) If vioscreen_ext_sample_id is None, try registration_code
4) If that fails, return a ValueError

2022-10-31 15:35 UTC, cassidysymons commented on microsetta_private_api/api/_survey.py
> +                         registration_code=None):
As above, we need to support both vioscreen_ext_sample_id and registration_code in this funciton.

2022-10-31 15:35 UTC, cassidysymons commented on microsetta_private_api/api/_vioscreen.py
> +def _get_session_by_account_details(account_id, source_id,
Shouldn't sample_id, registration_code, and timestamp all be optional parameters here?

2022-10-31 15:35 UTC, cassidysymons commented on microsetta_private_api/api/_vioscreen.py
> +def read_vioscreen_dietary_score(account_id, source_id,
Shouldn't sample_id, registration_code, and timestamp all be optional parameters here?

2022-10-31 15:35 UTC, cassidysymons commented on microsetta_private_api/api/_vioscreen.py
> +def read_vioscreen_food_components(account_id, source_id,
Shouldn't sample_id, registration_code, and timestamp all be optional parameters here?

2022-10-31 22:30 UTC, cassidysymons requested changes

2022-10-31 22:30 UTC, cassidysymons commented on microsetta_private_api/repo/survey_template_repo.py
> +                            "activation_code=%s AND "
```suggestion
                            "registration_code=%s AND "
```

2022-11-15 21:53 UTC, cassidysymons requested changes

2022-11-15 21:53 UTC, cassidysymons commented on microsetta_private_api/api/tests/test_api.py
> +            delta = relativedelta(month=now.month+2)
Please back out this change, the code as is - delta = relativedelta(months=now.month+2) - is a more concise approach.

2022-11-15 22:35 UTC, SyedAli-789 commented on microsetta_private_api/api/tests/test_api.py
> +            delta = relativedelta(month=now.month+2)
reverted the changes

2022-11-16 00:16 UTC, wasade commented on microsetta_private_api/repo/survey_template_repo.py
>              rows = cur.fetchall()
Should this be a `fetchone`?

2022-11-16 00:18 UTC, wasade commented on microsetta_private_api/repo/survey_template_repo.py
> +                            "GROUP BY vioscreen_registry.vio_id, "
Since we're selecting the most recent survey, is the `GROUP BY` needed?

2022-11-16 00:19 UTC, wasade commented on microsetta_private_api/repo/survey_template_repo.py
> +                            "GROUP BY vioscreen_registry.vio_id, "
Same here

2022-11-16 00:20 UTC, wasade commented on microsetta_private_api/repo/vioscreen_repo.py
> +    def get_vioscreen_sessions(self, account_id, source_id):
Can a unit test for this method be added?

2022-11-16 00:22 UTC, wasade commented on microsetta_private_api/repo/vioscreen_repo.py
> +                        (account_id, source_id))
I think this is the same as 

```sql
SELECT vs.*
FROM vioscreen_sessions vs 
JOIN vioscreen_registry vr ON vs.username = vr.vio_id
WHERE account_id=%s AND source_id=%s
```

2022-11-30 21:55 UTC, cassidysymons commented on microsetta_private_api/repo/vioscreen_repo.py
> +    def get_vioscreen_sessions(self, account_id, source_id):
@SyedAli-789 Please add unit tests for this function to repo/test/test_vioscreen.py. There should be one test that reflects the result of no rows being found and one test that reflects the result of one or more results being found.

2022-12-12 17:04 UTC, merged