Adding Perk type, send email with activation code, fundrazr Api
biocore/microsetta-private-api pull request #465
Opened 2022-10-10 22:03 UTC by Ram6911

2022-10-21 15:21 UTC, cassidysymons requested changes

2022-10-21 15:21 UTC, cassidysymons commented on microsetta_private_api/db/patches/0103.sql
> +-- Table: barcodes.daklapack_order_by_perk_type
We can't change a database patch that has already been merged into the codebase. Any and all database changes must be in a new patch file.

2022-10-21 15:21 UTC, cassidysymons commented on microsetta_private_api/server_config.json
> +  "Perks_type_ffq":"FFQ",
Please rename these to fit the existing capitalization scheme. Also, the proper descriptive names would be:
1) ffq
2) one kit
3) kit subscription

2022-10-21 15:21 UTC, cassidysymons commented on microsetta_private_api/repo/campaign_repo.py
> +        return (
Is there any reason you reformatted a lot of existing code in this file? It creates a substantial amount of excess work to determine which code changes are functional vs aesthetic and review them appropriately.

2022-10-21 15:21 UTC, cassidysymons commented on microsetta_private_api/repo/campaign_repo.py
> +                account_id = '00000000-0000-0000-0000-000000000000'
If an account doesn't exist, you set the account_id to a placeholder value. Once they sign up, how do we link their newly created account to this subscription?

2022-10-25 21:36 UTC, wasade commented on microsetta_private_api/db/patches/0104.sql
> +    id character varying COLLATE pg_catalog."default" NOT NULL,
What is the use of `COLLATE pg_catalog."default"`?

2022-10-25 21:37 UTC, wasade commented on microsetta_private_api/db/patches/0104.sql
> +        REFERENCES ag.account (id) MATCH SIMPLE
What is the need for `MATCH SIMPLE` and `ON UPDATE` and `ON DELETE`?

2022-10-25 21:37 UTC, wasade commented on microsetta_private_api/db/patches/0104.sql
> +TABLESPACE pg_default;
Is this necessary?

2022-10-25 21:37 UTC, wasade commented on microsetta_private_api/db/patches/0104.sql
> +    OWNER to postgres;
This won't work on production, is this necessary?

2022-10-25 21:37 UTC, wasade commented on microsetta_private_api/db/patches/0104.sql
> +    id character varying COLLATE pg_catalog."default" NOT NULL,
Same questions here with COLLATE and its other uses

2022-10-25 21:38 UTC, wasade commented on microsetta_private_api/db/patches/0104.sql
> +TABLESPACE pg_default;
Same question here as before, and with the `OWNER to postgres` statement a few lines below

2022-10-28 16:35 UTC, wasade commented on microsetta_private_api/admin/dacklapck_by_perk.py
> +    try:
Can exception handling be limited the relevant block of code? Otherwise it's going to be difficult to untangle where an exception was thrown

2022-10-28 18:13 UTC, wasade requested changes
In addition to the current comments, I want to stress that the logic of "add_perk_to_campaign" is very complex and the code paths should be enumerated with unit tests.

2022-10-28 18:13 UTC, wasade commented on microsetta_private_api/admin/dacklapck_by_perk.py
> +                if days_till_now.days >= 90:
I think this logic does not work with what's currently done in the campaign repo when someone orders a single sample. The campaign repo currently sets the planned ship date as `now`, which I think means it wouldn't pass this conditional?

2022-10-31 18:46 UTC, Ram6911 commented on microsetta_private_api/repo/campaign_repo.py
> +                    print(str(e))
I added a separate function for this.

2022-10-31 18:47 UTC, Ram6911 commented on microsetta_private_api/admin/daklapack_polling.py
> +# from microsetta_private_api.util.util import PerksType
Removed

2022-10-31 18:49 UTC, Ram6911 commented on microsetta_private_api/api/_account.py
> +    acct_repo.add_accnt_subscription(new_acct_id, body['email'])
As per Cassidy suggestion only One_year_plan will added to Subscription.

2022-10-31 18:49 UTC, Ram6911 commented on microsetta_private_api/db/patches/0103.sql
> +ALTER TABLE campaign.transaction ADD status VARCHAR;
Done

2022-10-31 18:50 UTC, Ram6911 commented on microsetta_private_api/db/patches/0104.sql
> +    code character varying COLLATE pg_catalog."default" NOT NULL,
Changed to activation code

2022-10-31 18:50 UTC, Ram6911 commented on microsetta_private_api/db/patches/0104.sql
> +    CONSTRAINT account_id_fk FOREIGN KEY (account_id)
Done

2022-10-31 18:51 UTC, Ram6911 commented on microsetta_private_api/repo/admin_repo.py
> +                ".dak_order_id=t2.daklapack_order"
Done

2022-10-31 18:53 UTC, Ram6911 commented on microsetta_private_api/repo/campaign_repo.py
> +            perk_type = SERVER_CONFIG["Perks_type_ffq"]
As per Cassidy suggestion default case set to None.

2022-10-31 18:57 UTC, Ram6911 commented on microsetta_private_api/db/patches/0103.sql
> +-- Table: barcodes.daklapack_order_by_perk_type
Updated

2022-10-31 18:58 UTC, Ram6911 commented on microsetta_private_api/server_config.json
> +  "Perks_type_ffq":"FFQ",
Updated

2022-10-31 18:59 UTC, Ram6911 commented on microsetta_private_api/repo/campaign_repo.py
> +        return (
This was happened while reformatted the file.

2022-10-31 19:02 UTC, Ram6911 commented on microsetta_private_api/db/patches/0104.sql
> +TABLESPACE pg_default;
Removed

2022-10-31 19:02 UTC, Ram6911 commented on microsetta_private_api/db/patches/0104.sql
> +    id character varying COLLATE pg_catalog."default" NOT NULL,
Removed

2022-10-31 19:02 UTC, Ram6911 commented on microsetta_private_api/db/patches/0104.sql
> +TABLESPACE pg_default;
Removed

2022-10-31 19:03 UTC, Ram6911 commented on microsetta_private_api/admin/dacklapck_by_perk.py
> +    For perk type 3 we have to send 4 kits in a year.
Renamed

2022-10-31 19:03 UTC, Ram6911 commented on microsetta_private_api/admin/dacklapck_by_perk.py
> +                    if order['no_of_kits'] <= 4:
Changed

2022-10-31 19:07 UTC, Ram6911 commented on microsetta_private_api/admin/dacklapck_by_perk.py
> +            open_dak_order_ids = a_repo.get_perk_type3_orders()
Renamed

2022-11-02 18:39 UTC, Ram6911 commented on microsetta_private_api/admin/dacklapck_by_perk.py
> +                if days_till_now.days >= 90:
Updated the file

2022-11-02 18:41 UTC, Ram6911 commented on microsetta_private_api/admin/dacklapck_by_perk.py
> +    try:
updated

2022-11-15 21:47 UTC, closed without merging