WIP: Return previous survey results
biocore/microsetta-private-api pull request #466
Opened 2022-10-11 21:20 UTC by charles-cowart

Missing unittests

2022-10-14 20:04 UTC, charles-cowart commented
Unittest not modified for a modified read_survey_template() method; it doesn't appear to currently have one.

2022-10-14 21:46 UTC, charles-cowart commented
@cassidysymons Sorry for the wait. This is now ready for review.

2022-10-18 14:06 UTC, cassidysymons requested changes

2022-10-18 14:06 UTC, cassidysymons commented on microsetta_private_api/repo/survey_template_repo.py
> +                result['percentage_completed'] = pc
It doesn't look like the percentage completed is getting added to the API response in _survey.py, can you double-check that, please?

2022-10-18 17:16 UTC, charles-cowart commented on microsetta_private_api/repo/survey_template_repo.py
> +                result['percentage_completed'] = pc
doh! Gotcha, sorry about that. I know exactly what happened.

2022-10-28 19:01 UTC, wasade commented on microsetta_private_api/repo/survey_template_repo.py
> +                    if latest_only and count > 1:
This is dependent on `survey_id not in results`, so won't `count` only ever be `1`?

2022-11-15 19:01 UTC, charles-cowart commented on microsetta_private_api/repo/survey_template_repo.py
> +                  ag.survey_answers as a,
Thanks for the catch, you are totally right!

2022-11-15 19:01 UTC, charles-cowart commented on microsetta_private_api/repo/survey_template_repo.py
> +                  c.survey_id = a.survey_id order by
Sure thing. reworked into a JOIN.

2022-11-15 19:39 UTC, charles-cowart commented on microsetta_private_api/repo/survey_template_repo.py
> +                    if latest_only and count > 1:
The idea here is that since the query can now return multiple surveys, and we want to restructure each survey in a semi-structured form, count could indeed be more than 1. Line 284 is just a short-circuit for when the caller just wants the latest survey only. Since the query results are ordered, the latest will be processed first and loop will break before the next latest survey is processed.

It's a little kludgey I admit. It might read better to process all the results and simply return the latest.

2022-11-15 19:47 UTC, charles-cowart commented on microsetta_private_api/api/_survey.py
> +            info.percentage_completed = results[0]['percentage_completed']
I'm not sure either. I thought I saw it come over in a test call. I will dig into this.

2022-11-16 00:11 UTC, wasade requested changes

2022-11-16 00:11 UTC, wasade commented on microsetta_private_api/repo/survey_template_repo.py
> +        sql = f"""select a.survey_id, a.survey_question_id, a.response,
It is not safe to use string formatting for SQL queries, please pass arguments through `.execute`

2022-11-16 00:11 UTC, wasade commented on microsetta_private_api/repo/survey_template_repo.py
> +        sql = f"""select a.survey_id, a.survey_question_id, a.response,
Please also use `JOIN` rather than doing it in `WHERE`. And in general, please format the queries for readability as it is really hard to understand what's going on here

2022-11-16 00:11 UTC, wasade commented on microsetta_private_api/repo/survey_template_repo.py
> +                  survey_id = {survey_template_id} group by
It is not safe to use string formatting with SQL queries, please pass arguments to `.execute`

2022-11-16 00:11 UTC, wasade commented on microsetta_private_api/repo/survey_template_repo.py
> +        # adding indexes to these individual columns may improve performance.
Should this be part of a patch?

2022-11-16 00:11 UTC, wasade commented on microsetta_private_api/repo/tests/test_survey_template_repo.py
> +            # repeat the test, except return all responses.
I don't believe this actually exercises the case of having multiple surveys. Please test this specifically as it is a large change to the system, and may easily have unexpected consequences

2022-11-16 01:50 UTC, charles-cowart commented on microsetta_private_api/repo/survey_template_repo.py
> +        sql = f"""select a.survey_id, a.survey_question_id, a.response,
Is there a technical reason to prefer JOIN over WHERE? I don't believe there is a performance difference, given that this is an inner join, not a left or other outer join.

2022-11-16 01:51 UTC, wasade commented
Project conventions

On Tue, Nov 15, 2022, 17:50 Charles Cowart ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In microsetta_private_api/repo/survey_template_repo.py
> <https://github.com/biocore/microsetta-private-api/pull/466#discussion_r1023423226>
> :
>
> > +                  ag.group_questions b where
> +                  a.survey_group = b.survey_group and
> +                  survey_id = {survey_template_id} group by
> +                  survey_template_id"""
> +
> +        total_count = None
> +
> +        with self._transaction.cursor() as cur:
> +            cur.execute(sql)
> +            total_count = cur.fetchone()[1]
> +
> +        # adding indexes to these individual columns may improve performance.
> +        #     ag.survey_answers.survey_question_id
> +        #     ag.surveys.survey_id
> +
> +        sql = f"""select a.survey_id, a.survey_question_id, a.response,
>
> Is there a technical reason to prefer JOIN over WHERE? I don't believe
> there is a performance difference, given that this is an inner join, not a
> left or other outer join.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/biocore/microsetta-private-api/pull/466#discussion_r1023423226>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AADTZMV4DK56247PXKLG4O3WIQ4YFANCNFSM6AAAAAARCVWOZA>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2022-11-16 02:09 UTC, wasade commented
Thanks!

On Tue, Nov 15, 2022, 18:06 Charles Cowart ***@***.***> wrote:

> Will pull in the month fix from Cassidy's branch, reformat the query to
> use JOINs over WHEREs, and I'll review and enhance the test in question
> later tonight or earlier tomorrow.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/biocore/microsetta-private-api/pull/466#issuecomment-1316180939>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AADTZMQDLFZZGV3WT4PZPTDWIQ6TTANCNFSM6AAAAAARCVWOZA>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2022-11-16 22:48 UTC, charles-cowart commented
@cassidysymons @wasade All feedback should be incorporated. All tests passing. Please feel free to review.

2022-11-23 01:56 UTC, charles-cowart commented
Per @wasade's request, we want some additional testing to confirm push/pull when multiple surveys of template n are available, are the results passed to and from Qiita intelligently.

2022-12-02 23:28 UTC, cassidysymons commented
This PR should also be against master-overhaul, not master.

2022-12-06 21:25 UTC, charles-cowart commented
Closing. Superseded by #489

2022-12-06 21:25 UTC, closed without merging