Adding Data and Bio Consent through DB
biocore/microsetta-private-api pull request #476
Opened 2022-11-01 08:09 UTC by raginirai553

2022-11-09 23:45 UTC, cassidysymons requested changes

2022-11-09 23:45 UTC, cassidysymons commented on microsetta_private_api/repo/consent_repo.py
> +            cur.execute("SELECT " + self.doc_read_cols + " FROM "
The way this query is written, it will return every single document for a given language tag, even if some of them have been replaced. We only want to return the most recent version of each document type.

2022-11-09 23:45 UTC, cassidysymons commented on microsetta_private_api/api/_consent.py
> +    return jsonify(data), 200
Shouldn't this return a 404 error if data is None, rather than an HTTP code of 200?

2022-11-09 23:45 UTC, cassidysymons commented on microsetta_private_api/repo/consent_repo.py
> +                        "LIKE %s ORDER BY sign_date DESC",
Why are you using LIKE rather than = here?

2022-11-09 23:45 UTC, cassidysymons commented on microsetta_private_api/api/_consent.py
> +        data = [x.to_api() for x in documents]
Since get_consent_document() can only return one result, wouldn't it be clearer to express without the for/in loop?

2022-11-09 23:45 UTC, cassidysymons commented on microsetta_private_api/api/_consent.py
> +    res = True
Is it necessary to have a default state here? Or to turn the question around, in what situation will ConsentRepo.is_consent_required not return an actionable result?

2022-11-09 23:45 UTC, cassidysymons commented on microsetta_private_api/api/_consent.py
> +def sign_consent_doc(account_id, source_id, consent_type, body, token_info):
Since ConsentRepo.sign_consent can raise NotFound, it would be good to catch those and express them appropriately in the response, if they were to occur.

2022-11-09 23:45 UTC, cassidysymons commented on microsetta_private_api/db/patches/0106.sql
> +     "street", "city", "post_code", "country_code", "preferred_language",
There's no reason to insert street, city, post_code, country_code, preferred_language, address_verified, or cannot_geocode for the consent dummy account.

2022-11-09 23:45 UTC, cassidysymons commented on microsetta_private_api/db/patches/0106.sql
> +    VALUES ('Adolescent Consent - Biospecimen', 'en_US', NOW(), '<p class="consent_title">
For all of the various consent types, can we stick to [age-group]_[type]? The various permutations should be as follows:
adolescent_biospecimen
adolescent_data
adult_biospecimen
adult_data
child_biospecimen
child_data
parent_biospecimen
parent_data

Including "Consent" in the string is redundant for certain types and inaccurate for others (child/adolescent docs are technically assent, not consent).

Please also make this change in the Interface PR so that everything matches up between the two.

2022-11-09 23:45 UTC, cassidysymons commented on microsetta_private_api/model/consent.py
> +        date_time = datetime.now()
Shouldn't the date_time be coming from the record in the database rather than now()?

2022-11-09 23:45 UTC, cassidysymons commented on microsetta_private_api/model/consent.py
> +        assent_obtainer = input_dict.get("assent_obtainer", None)
```suggestion
        parent_name_1 = input_dict.get("parent_1_name")
        parent_name_2 = input_dict.get("parent_2_name")
        deceased_parent = input_dict.get("deceased_parent")
        assent_obtainer = input_dict.get("assent_obtainer")
```
get() will return None by default if the key doesn't exist, no need to declare it.

2022-11-09 23:45 UTC, cassidysymons commented on microsetta_private_api/repo/consent_repo.py
> +        getattr(r, 'account_id', None),
It should be impossible for a consent document to not have an account_id.

2022-11-10 02:49 UTC, raginirai553 commented on microsetta_private_api/api/_consent.py
> +    return jsonify(data), 200
Corrected!

2022-11-10 02:50 UTC, raginirai553 commented on microsetta_private_api/api/_consent.py
> +        data = [x.to_api() for x in documents]
Corrected!

2022-11-10 03:43 UTC, raginirai553 commented on microsetta_private_api/db/patches/0106.sql
> +    VALUES ('Adolescent Consent - Biospecimen', 'en_US', NOW(), '<p class="consent_title">
Corrected!

2022-11-10 03:51 UTC, raginirai553 commented on microsetta_private_api/model/consent.py
> +        assent_obtainer = input_dict.get("assent_obtainer", None)
Corrected!

2022-11-10 04:01 UTC, raginirai553 commented on microsetta_private_api/repo/consent_repo.py
> +            cur.execute("SELECT " + self.doc_read_cols + " FROM "
@cassidysymons The query is designed always fetch only one record of latest consent document for each type. self.doc_read_cols contains distinct constraint on consent_type ensuring unique document for each consent further combined with order by clause as per date_time in descending order ensuring that we always get latest consent documents.

2022-11-10 04:35 UTC, raginirai553 commented on microsetta_private_api/repo/consent_repo.py
> +                        "LIKE %s ORDER BY sign_date DESC",
We are using like query instead of equals becasue the exact consent type is not known at this instance. There are broadly two classifications of consent i.e., data and biospecimen. While checking the consent status for any source, the age range for the source is not known at the interface end. Therefore, one cannot make any exact calls for particular consent from the interface. However, the broader category i.e., data or biospecimen is known. Although there are workarounds including extraction of age_range from the source table given source id, programattically create string for exact consent_document type and look for the said document in the query. However, to avoid the workaround, accurate match can be found on basis of consent_type LIKE and source_id, since source_id is a foreign key in consent_audit table. 
Further, there may exist multiple consents provided by a source but we intend to find the consent from one of the broader categories, that too latest signed.

2022-11-10 04:35 UTC, raginirai553 commented on microsetta_private_api/api/_consent.py
> +    res = True
Removed the default initialization.

2022-11-10 04:42 UTC, raginirai553 commented on microsetta_private_api/api/_consent.py
> +def sign_consent_doc(account_id, source_id, consent_type, body, token_info):
Try-except block added to handle errors appropriately.

2022-11-10 04:42 UTC, raginirai553 commented on microsetta_private_api/db/patches/0106.sql
> +     "street", "city", "post_code", "country_code", "preferred_language",
Since all these fields have NOT NULL constraints applied in the database, it was necessary to include these in the DB Patch.

2022-11-10 04:42 UTC, raginirai553 commented on microsetta_private_api/model/consent.py
> +        date_time = datetime.now()
The purpose of this static method is to create consent document object from the post request by admin to create new consent and therefore, date_time is generated using now(). This method is not used right now and is a provision for future.

2022-11-10 04:42 UTC, raginirai553 commented on microsetta_private_api/repo/consent_repo.py
> +        getattr(r, 'account_id', None),
This was written for testing purposes. Changes have been reverted.

2022-11-10 05:30 UTC, raginirai553 commented on microsetta_private_api/repo/consent_repo.py
> +            cur.execute("SELECT " + self.doc_read_cols + " FROM "
@cassidysymons I have tested it few times already and it always returns the latest consent content

2022-11-10 16:59 UTC, cassidysymons commented on microsetta_private_api/repo/consent_repo.py
> +            cur.execute("SELECT " + self.doc_read_cols + " FROM "
Sorry, I missed the distinct clause in read_cols. Looks good.

2022-11-10 17:08 UTC, cassidysymons commented on microsetta_private_api/api/_consent.py
>      return jsonify(data), 200
This can be more concise:

```
    document = consent_repo.get_consent_document(consent_id)
    
if document:
    data = document.to_api()
    return jsonify(data), 200
else:
    return jsonify(code=404, message=CONSENT_DOC_NOT_FOUND_MSG) , 404
```

2022-11-10 17:13 UTC, cassidysymons commented on microsetta_private_api/db/patches/0106.sql
> +     "street", "city", "post_code", "country_code", "preferred_language",
Ah, for some reason I thought those fields were nullable. Please just change address_verified to false.

2022-11-10 17:49 UTC, raginirai553 commented on microsetta_private_api/repo/consent_repo.py
> +                        "LIKE %s ORDER BY sign_date DESC",
No, its all working as expected

2022-11-10 17:52 UTC, raginirai553 commented on microsetta_private_api/api/_consent.py
>      return jsonify(data), 200
Updated!

2022-11-10 17:53 UTC, raginirai553 commented on microsetta_private_api/db/patches/0106.sql
> +     "street", "city", "post_code", "country_code", "preferred_language",
Changed!

2022-11-11 01:57 UTC, merged