Survey database update v2
biocore/microsetta-private-api pull request #489
Opened 2022-11-22 17:32 UTC by charles-cowart

Alternative approach to survey/data migration that preserves retired survey templates/groups.
Working on final four broken unittests and adding additional tests as appropriate.

2022-11-22 22:31 UTC, charles-cowart commented on microsetta_private_api/repo/survey_answers_repo.py
> +                cur.execute("SELECT EXISTS (SELECT polyphenol_ffq_id FROM "
Remove potential SQL injection vectors

2022-11-22 22:38 UTC, charles-cowart commented on microsetta_private_api/db/migration_support.py
> +        "0105.sql": migrate_107.__func__,
0107.sql

2022-11-22 22:39 UTC, wasade requested changes
Many of the comments from #474 appear outstanding, could those please be addressed as well?

2022-11-22 22:39 UTC, wasade commented on microsetta_private_api/db/migration_support.py
> +    def migrate_107(TRN):
It doesn't look like this makes any changes, is it necessary?

2022-11-22 22:39 UTC, wasade commented on microsetta_private_api/db/patches/0107.sql
> +update ag.survey_question set american = 'How often do you consume at least 2-3 servings of fruit in a day? (1 serving = 1⁄2 cup (1 serving = 1⁄2 cup fruit juice.)' where survey_question_id = 61;
Unusual character "1⁄2"

2022-11-22 22:39 UTC, wasade commented on microsetta_private_api/db/patches/0107.sql
> +alter table ag.ag_login_surveys add column survey_template_id integer;
Can an english description of what the table creations are doing be added please?

2022-11-29 22:11 UTC, charles-cowart commented on microsetta_private_api/repo/survey_answers_repo.py
> +                cur.execute("SELECT EXISTS (SELECT polyphenol_ffq_id FROM "
No potential SQL-injection vectors appeared when reviewing the changes in this PR. Tentatively calling it closed.

2022-11-29 22:11 UTC, charles-cowart commented on microsetta_private_api/db/migration_support.py
> +        "0105.sql": migrate_107.__func__,
Fixed.

2022-11-29 22:12 UTC, charles-cowart commented on microsetta_private_api/db/migration_support.py
> +    def migrate_107(TRN):
Will remove this last, once it's demonstrated that it's not needed.

2022-11-29 22:13 UTC, charles-cowart commented on microsetta_private_api/db/migration_support.py
> +        "0105.sql": migrate_107.__func__,
Noted.

2022-11-29 22:16 UTC, charles-cowart commented on microsetta_private_api/db/patches/0107.sql
> +update ag.survey_question set american = 'How often do you consume at least 2-3 servings of fruit in a day? (1 serving = 1⁄2 cup (1 serving = 1⁄2 cup fruit juice.)' where survey_question_id = 61;
Removed all non-ASCII characters and replaced them with their ASCII equivalents, except where 'crème fraiche' was used.

2022-11-29 22:16 UTC, charles-cowart commented on microsetta_private_api/db/patches/0107.sql
> +alter table ag.ag_login_surveys add column survey_template_id integer;
Done!

2022-11-29 22:16 UTC, charles-cowart commented on microsetta_private_api/db/patches/0107.sql
> +alter table ag.ag_login_surveys add column survey_template_id integer;
Working on it.

2022-11-29 22:18 UTC, wasade commented on microsetta_private_api/repo/survey_answers_repo.py
> +                cur.execute("SELECT EXISTS (SELECT polyphenol_ffq_id FROM "
Pass in arguments to `.execute`, do not use string formatting

2022-11-29 22:25 UTC, charles-cowart commented on microsetta_private_api/repo/survey_answers_repo.py
> +                cur.execute("SELECT EXISTS (SELECT polyphenol_ffq_id FROM "
Just to be clear, we're arguing there's a difference between:
> cur.execute("SELECT EXISTS (SELECT polyphenol_ffq_id FROM ag.polyphenol_ffq_registry WHERE polyphenol_ffq_id='%s')" % survey_id)
and
> cur.execute("SELECT EXISTS (SELECT polyphenol_ffq_id FROM ag.polyphenol_ffq_registry WHERE polyphenol_ffq_id=%s)" % (survey_id,))

2022-11-29 22:29 UTC, wasade commented on microsetta_private_api/repo/survey_answers_repo.py
> +                cur.execute("SELECT EXISTS (SELECT polyphenol_ffq_id FROM "
Yes, see https://stackoverflow.com/a/45128973/19741

2022-11-29 22:29 UTC, wasade commented on microsetta_private_api/repo/survey_answers_repo.py
> +                cur.execute("SELECT EXISTS (SELECT polyphenol_ffq_id FROM "
We are not arguing: this pull request will not be merged with unsafe use of SQL.

2022-11-29 22:40 UTC, charles-cowart commented on microsetta_private_api/repo/survey_answers_repo.py
> +                cur.execute("SELECT EXISTS (SELECT polyphenol_ffq_id FROM "
@wasade right, I didn't mean to imply we were arguing, just that there is in fact a difference between those two similar looking statements.

2022-11-29 23:00 UTC, wasade commented on microsetta_private_api/repo/survey_answers_repo.py
> +            cur.execute(sql)
This doesn't require a tuple expansion?

2022-11-29 23:01 UTC, wasade commented on microsetta_private_api/repo/survey_answers_repo.py
> +            cur.execute(sql)
Same here re: tuple expansion? This is passing `cur.execute((foo, bar))`, but it should be `cur.execute(foo, bar)`

I haven't checked other areas of code so this may occur in additional places

2022-11-29 23:05 UTC, charles-cowart commented on microsetta_private_api/repo/survey_answers_repo.py
> +            cur.execute(sql)
doh. You literally caught that at the same time as CI. nice!

2022-11-29 23:31 UTC, charles-cowart commented on microsetta_private_api/repo/survey_answers_repo.py
> +            cur.execute(sql)
Actually it didn't require the dereference *; instead it needed to be converted into a proper tuple from a list.

2022-11-29 23:32 UTC, charles-cowart commented on microsetta_private_api/repo/survey_answers_repo.py
> +            cur.execute(sql)
three in total. just fixed them and ran them through tests locally. Should be going through CI right now.

2022-11-30 01:04 UTC, charles-cowart commented on microsetta_private_api/db/patches/0107.sql
> +alter table ag.ag_login_surveys add column survey_template_id integer;
Added update statements to populate remove survey rows in ag_login_surveys, added no null constraint to the survey_template_id column, and updated inserts in the code and tests to support the new requirement. Tentatively closing.

2022-11-30 01:04 UTC, charles-cowart commented on microsetta_private_api/repo/survey_answers_repo.py
> +                cur.execute("SELECT EXISTS (SELECT polyphenol_ffq_id FROM "
@wasade tentatively resolved. all tests working.

2022-11-30 01:05 UTC, wasade commented on microsetta_private_api/repo/survey_answers_repo.py
> +                cur.execute("SELECT EXISTS (SELECT polyphenol_ffq_id FROM "
Great, thanks!

2022-11-30 01:05 UTC, charles-cowart commented on microsetta_private_api/repo/survey_answers_repo.py
> +            cur.execute(sql)
tentatively closed (see related comment above).

2022-11-30 01:14 UTC, charles-cowart commented
@cassidysymons would you still prefer this PR to point to master-overhaul instead of master? I'm reviewing old comments from the v1 pr.

2022-11-30 01:15 UTC, cassidysymons commented
@charles-cowart Yes, please point it at master-overhaul. Thanks!

2022-12-01 16:57 UTC, cassidysymons commented
@charles-cowart Why are you still migrating the old surveys into new templates? Didn't the idea of retiring templates eliminate the need for that migration?

2022-12-01 17:45 UTC, charles-cowart commented
@cassidysymons The idea of retiring templates was to allow us to migrate data without having to perform a lot of CRUD operations over the legacy survey data. Otherwise we'd need to delete legacy template information and migrate all legacy responses over to new templates. This is a large operation over valuable data and can't be undone, as Daniel pointed out.

The update code is relatively straightforward to audit, reuses survey create and delete functions, and has unit tests. This should help to inspire confidence in its robustness. Creating new surveys allows us to migrate and test non-destructively with respect to the legacy data.

get_survey_metadata() doesn't return survey_ids along with the survey metadata it returns, so migrating it on the fly seem s possible, but it would break the service if a user or developer (now or in the future) expects a BASIC_INFO template to exist and it doesn't.

2022-12-01 17:52 UTC, wasade commented
I'm also surprised by the need for migration. The `ag.survey_answers` table does not care about what template a `survey_question_id` is associated with. I thought the plan was to update the associations with `ag.survey_question` and `ag.group_questions`, and to not touch `ag.survey_answers`

2022-12-01 17:56 UTC, cassidysymons commented
@charles-cowart When we discussed the strategy of retiring templates, we discussed adding survey_template_id to ag_login_surveys, so that the only migration necessary would be adding the template_id to that table, rather than creating new records for the old responses. Did something come up that made that unfeasible?

@wasade Based on [the comments for this migration that Dan Hakim wrote](https://github.com/biocore/microsetta-private-api/commit/9f96eb59ef749100d476dfbc3d54df2fdcb40361), we do need to be able to determine the survey_template_id from a record in ag_login_surveys. However, retroactively adding it via a migration seems like the least invasive option at our disposal.

2022-12-01 17:58 UTC, wasade commented
I thought we were making `survey_template_id` explicit in `ag_login_surveys` in this PR. Maybe we're mincing words, but I wouldn't consider that a migration as we aren't moving data but creating it.

2022-12-01 18:00 UTC, cassidysymons commented
That was my understanding too, so I think we only have a semantics difference. I think the change would need to use the migration_support.py functionality as it would be incredibly complex to achieve entirely via sql, but yes, it's creating data, not moving it.

2022-12-01 19:38 UTC, charles-cowart commented
> @charles-cowart When we discussed the strategy of retiring templates, we discussed adding survey_template_id to ag_login_surveys, so that the only migration necessary would be adding the template_id to that table, rather than creating new records for the old responses. Did something come up that made that unfeasible?

My understanding was that we'd be able to create the new surveys on-demand if we called this new functionality in get_survey_metadata(), leaving the legacy data alone. Or we could call it once for every barcode in migration. The advantages of the latter is we process a barcode once and only once, without having to add a column or some other metadata to denote that we've migrated a barcode and don't do it again on-demand. However we always needed to maintain the constraint that a survey_id is associated with one and only one template_id permanently. It breaks the code if we don't, and it makes the data inconsistent in survey_answers.

2022-12-01 19:41 UTC, charles-cowart commented
> That was my understanding too, so I think we only have a semantics difference. I think the change would need to use the migration_support.py functionality as it would be incredibly complex to achieve entirely via sql, but yes, it's creating data, not moving it.

The population of the new survey_template_id column in ag_login_surveys is actually done in the 0108.sql file. I generate three temp tables at the top of the file and use the successive results to populate the column before deleting them.

2022-12-01 19:42 UTC, cassidysymons commented
If we add the survey_template_id to ag_login_surveys, and leave all of the old survey templates intact (but retired), why do we need to do any sort of migration?

2022-12-01 19:49 UTC, charles-cowart commented
Confirmed the lone error in tests is caused by comparing the observed results of _migrate_responses() with the expected values. The results are identical, but self.assertDictEqual(obs, filled_surveys) fails because elements are in different internal order. Will look into and resolve after the call.

2022-12-01 19:57 UTC, charles-cowart commented
> If we add the survey_template_id to ag_login_surveys, and leave all of the old survey templates intact (but retired), why do we need to do any sort of migration?

We aren't migrating data, but we do need to copy it. For survey x of template 'Primary Questionnaire', we need to take those 100 odd questions, filter out the 'Undetermined' non-answers, create new templates with the right subset of questions in each, padding out those templates with their own 'Undetermined' answers for the questions that were not answered, and create them with survey X's timestamp, source id, sample_id, account_id, etc.

2022-12-06 21:28 UTC, charles-cowart commented
Closed #466 as this PR supersedes it. Specifically, if we remove the component that migrates old surveys into new templates, what is left is code that’s basically a better version of the code written in #466 to populate surveys with legacy answers, with better tests. Since they both touch read_survey_template() in the same way, it’s really one or the other. The only thing left to keep from #466 was the percentage completed code, so I folded it in. I also added additional tests for the Qiita-related functionality as requested in #466.

2022-12-06 22:19 UTC, charles-cowart commented on microsetta_private_api/admin/tests/test_admin_api.py
> +
add commit here as well.

2022-12-06 22:28 UTC, charles-cowart commented on microsetta_private_api/admin/tests/test_admin_api.py
> +        # it appears in query results.
We will want to keep GENDER_v2 as-is and push it to Qiita. It's not private an (BImore.
We have no plans for any private short names at this time? - privacy should not be based on PM_ and instead should be based on EBI submissions. see: EBI_REMOVE (EBI_REMOVE alone is not ground truth for privacy. Any free-text answer is also private)
About-yourself (116) needs to be unretired and stored in template 10.

2022-12-06 22:31 UTC, charles-cowart commented on microsetta_private_api/admin/tests/test_admin_api.py
> +
Add commit here too.

2022-12-06 22:40 UTC, charles-cowart commented on microsetta_private_api/api/tests/test_api.py
> +        date = now + datetime.timedelta(days=61)
Lost Cassidy's fix.

2022-12-06 22:42 UTC, charles-cowart commented on microsetta_private_api/api/tests/test_integration.py
>                               "Couldn't read answer from db in en_GB")
Consider something that's actually different

2022-12-06 22:54 UTC, charles-cowart commented on microsetta_private_api/repo/metadata_repo/_repo.py
> +            # each as_series represents the aggregated shortname, value
Any code interacting w/Qiita should return the value from the survey with the smallest time delta to the timestamp associated with the sample (see the timestamp in ag_login_surveys). With respect to the UI, we want the latest answer.

2022-12-06 22:57 UTC, charles-cowart commented on microsetta_private_api/repo/metadata_repo/_repo.py
> +
explain that behavior has changed and that this is no longer a hack but a feature. however for legacy data we don't know how to resolve it perhaps? because we don't have the collected timestamps. Are there timestamps associated with all surveys?

2022-12-06 23:03 UTC, charles-cowart commented on microsetta_private_api/repo/survey_answers_repo.py
> +                               creation_time=None):
remove creation_time as a parameter.

2022-12-06 23:03 UTC, charles-cowart commented on microsetta_private_api/repo/survey_answers_repo.py
> +                cur.execute("INSERT INTO ag_login_surveys "
this can be adjusted as well since we are removing creation_time

2022-12-06 23:04 UTC, charles-cowart commented on microsetta_private_api/repo/admin_repo.py
Is this code vestigial?

2022-12-06 23:13 UTC, charles-cowart commented on microsetta_private_api/repo/tests/test_survey_template_repo.py
> +        with Transaction() as t:
potentially merge these back into single test method

2022-12-06 23:18 UTC, charles-cowart commented on microsetta_private_api/repo/survey_template_repo.py
> +        '''
Make sure we distinguish between different sources in an account_id. Let's not use account_id and use only source_id so the answers are user-associated and not account associated.

2022-12-06 23:27 UTC, wasade requested changes

2022-12-06 23:27 UTC, wasade commented on microsetta_private_api/repo/survey_template_repo.py
> +        if int(survey_template_id) in self.SURVEY_INFO:
Please ensure `survey_template_id` is the correct type before calling this method

2022-12-06 23:27 UTC, wasade commented on microsetta_private_api/repo/survey_template_repo.py
> +        :param account_id: An account
This isn't a parameter for the method

2022-12-06 23:27 UTC, wasade commented on microsetta_private_api/repo/survey_template_repo.py
> +            if cur.rowcount == 0:
it looks like this conditional is based on a stale variable as the `cur` call is commented out

2022-12-06 23:27 UTC, wasade commented on microsetta_private_api/repo/survey_template_repo.py
> +            if cur.rowcount == 0:
...rather unused `cur`

2022-12-06 23:27 UTC, wasade commented on microsetta_private_api/repo/survey_template_repo.py
> +                response_type = row[3]
are these indices assured to be stable given that a `SELECT *` is used? What about a dict cursor or enforcing the order by specifying the columns in the select?

2022-12-06 23:27 UTC, wasade commented on microsetta_private_api/repo/survey_template_repo.py
> +    def migrate_responses(self, account_id, survey_template_id):
This should be by source not account

2022-12-06 23:27 UTC, wasade commented on microsetta_private_api/repo/survey_template_repo.py
> +            if cur.rowcount == 0:
Same comment here with the unused `cur`

2022-12-06 23:27 UTC, wasade commented on microsetta_private_api/repo/survey_template_repo.py
> +                response_type = row[4]
Same comment here regarding magic values

2022-12-06 23:27 UTC, wasade commented on microsetta_private_api/repo/survey_template_repo.py
> +            raise ValueError("survey_ids is not a list of survey ids")
Please have the caller of this method ensure the data are of the correct type

2022-12-06 23:27 UTC, wasade commented on microsetta_private_api/repo/survey_template_repo.py
> +        if len(survey_ids) == 0 or '' in survey_ids or None in survey_ids:
Please handle this upstream

2022-12-06 23:27 UTC, wasade commented on microsetta_private_api/repo/survey_template_repo.py
> +                # If survey_id isn't a valid UUID, a ValueError will be
There are valid survey IDs which are not UUID

2022-12-06 23:27 UTC, wasade commented on microsetta_private_api/repo/survey_template_repo.py
> +    def _remote_survey_template_id_from_survey_id(self, survey_id):
I'm not sure I undersand this function. Don't we know what template a survey ID is associated with and therefore don't need to test its existence in multiple registries?

2022-12-06 23:27 UTC, wasade commented on microsetta_private_api/repo/survey_template_repo.py
> +            # note these ids are unique string ids, not integer ids.
The survey ID specifically right?

2022-12-06 23:27 UTC, wasade commented on microsetta_private_api/repo/tests/test_survey_template_repo.py
> +                sar._generate_empty_survey(10001)
Can the static variable for this survey be used?

2022-12-06 23:27 UTC, wasade commented on microsetta_private_api/repo/tests/test_survey_template_repo.py
> +            try:
```suggestion
```

2022-12-06 23:27 UTC, wasade commented on microsetta_private_api/repo/tests/test_survey_template_repo.py
> +                pass
```suggestion
```

2022-12-06 23:27 UTC, wasade commented on microsetta_private_api/repo/tests/test_survey_template_repo.py
> +                sr.create_source(HUMAN_SOURCE)
```suggestion
            sr.create_source(HUMAN_SOURCE)
```

2022-12-06 23:27 UTC, wasade commented on microsetta_private_api/repo/tests/test_survey_template_repo.py
> +                pass
Please ensure the test database is cleaned up

2022-12-06 23:27 UTC, wasade commented on microsetta_private_api/repo/tests/test_survey_template_repo.py
> +    def test_migrate_responses(self):
I'm not reviewing this test as we had discussed making this function per source not per account

2022-12-07 18:14 UTC, charles-cowart commented on microsetta_private_api/api/tests/test_integration.py
>                               "Couldn't read answer from db in en_GB")
Note: Low priority.

2022-12-07 22:27 UTC, charles-cowart commented on microsetta_private_api/db/migration_support.py
> +    def migrate_107(TRN):
Removed.

2022-12-07 22:31 UTC, charles-cowart commented on microsetta_private_api/admin/tests/test_admin_api.py
> +        # it appears in query results.
Resolved.

2022-12-07 22:31 UTC, charles-cowart commented on microsetta_private_api/admin/tests/test_admin_api.py
> +
Resolved.

2022-12-07 22:38 UTC, charles-cowart commented on microsetta_private_api/repo/survey_answers_repo.py
> +                               creation_time=None):
Resolved.

2022-12-07 22:39 UTC, charles-cowart commented on microsetta_private_api/repo/survey_answers_repo.py
> +                cur.execute("INSERT INTO ag_login_surveys "
Resolved.

2022-12-07 22:53 UTC, charles-cowart commented on microsetta_private_api/repo/metadata_repo/_repo.py
>  TEMPLATES_TO_IGNORE = {10001, 10002, 10003, 10004, None}
Resolved.

2022-12-07 22:57 UTC, charles-cowart commented on microsetta_private_api/repo/survey_template_repo.py
> +        :param account_id: An account
Resolved.

2022-12-07 23:22 UTC, charles-cowart commented on microsetta_private_api/repo/survey_template_repo.py
> +                response_type = row[3]
Well the SELECT * is just a thin wrapper over the real query to allow ordering by creation time and question id. The UNION of the two queries inside is what explicitly defines the columns in the result. However I'll keep it in mind. This query will need to be reworked anyway to allow for closest time delta to the survey timestamp.

2022-12-08 06:03 UTC, charles-cowart commented on microsetta_private_api/api/tests/test_api.py
> +        date = now + datetime.timedelta(days=61)
Resolved.

2022-12-08 06:46 UTC, charles-cowart commented on microsetta_private_api/repo/survey_template_repo.py
> +                        (account_id, mfr_id, None, source_id, 10002))
Resolved

2022-12-08 06:46 UTC, charles-cowart commented on microsetta_private_api/repo/survey_template_repo.py
> +                             10004))
Resolved

2022-12-08 06:46 UTC, charles-cowart commented on microsetta_private_api/repo/survey_template_repo.py
> +                            (account_id, vioscreen_id, -1, source_id, 10001))
Resolved

2022-12-08 06:47 UTC, charles-cowart commented on microsetta_private_api/repo/survey_template_repo.py
> +                             10003))
Resolved

2022-12-08 06:54 UTC, charles-cowart commented on microsetta_private_api/repo/survey_template_repo.py
> +        if int(survey_template_id) in self.SURVEY_INFO:
Removed. The only caller for this method by its nature only passes valid template ids of local surveys.

2022-12-09 06:49 UTC, charles-cowart commented on microsetta_private_api/api/tests/test_integration.py
>                               "Couldn't read answer from db in en_GB")
removing from consideration for this PR.

2022-12-09 07:11 UTC, charles-cowart commented on microsetta_private_api/repo/admin_repo.py
> +        template_ids = list(set([x[1] for x in template_ids]))
template_ids in this case is actually a list of (survey_id, survey_template_id) tuples. In the case where we just want a list of template_ids, we need the list comprehension to extract that out. The set is there to remove potential duplicate template ids since there might now be more than one survey of template type N.

2022-12-09 07:17 UTC, charles-cowart commented on microsetta_private_api/repo/tests/test_survey_template_repo.py
> +                sar._generate_empty_survey(10001)
Resolved/

2022-12-09 19:48 UTC, charles-cowart commented on microsetta_private_api/repo/metadata_repo/_repo.py
> +            # each as_series represents the aggregated shortname, value
Resolved.

2022-12-09 19:49 UTC, charles-cowart commented on microsetta_private_api/repo/tests/test_survey_template_repo.py
> +        with Transaction() as t:
This is used in a couple of different tests. Will leave as is.

2022-12-09 19:49 UTC, charles-cowart commented on microsetta_private_api/repo/survey_template_repo.py
> +        '''
Resolved.

2022-12-09 19:51 UTC, charles-cowart commented on microsetta_private_api/repo/survey_template_repo.py
> +    def migrate_responses(self, account_id, survey_template_id):
Resolved.

2022-12-09 19:56 UTC, charles-cowart commented on microsetta_private_api/repo/admin_repo.py
> +
template_ids as a list of tuples is used further below. It wouldn't be good to strip the survey_ids out at this time.

2022-12-09 19:56 UTC, charles-cowart commented on microsetta_private_api/repo/admin_repo.py
> +            if survey_template_id not in [x[1] for x in template_ids]:
Related to above issue. template_ids is needed as a tuple below this line.

2022-12-09 19:58 UTC, cassidysymons commented on microsetta_private_api/repo/survey_template_repo.py
> +            # what if there are multiple template Xs? Should we take the
For anything historical, there won't be more than one. Per the way surveys are associated with a source and [this comment](https://github.com/biocore/microsetta-interface/blob/master/microsetta_interface/implementation.py#L1566) explaining the current thought-process, you can safely count on one record.

This will need to be re-thought when we eventually change the metadata process to update, rather than just insert, but it's beyond the scope of this PR.

2022-12-09 20:02 UTC, charles-cowart commented on microsetta_private_api/repo/survey_template_repo.py
> +                           WHERE  ag_login_id = %s""", (account_id,))
Resolved. I believe this code was part of a commented out check that was removed.

2022-12-09 20:03 UTC, charles-cowart commented on microsetta_private_api/repo/survey_template_repo.py
> +            if cur.rowcount == 0:
Resolved. I believe this code was part of a commented out check that was removed.

2022-12-09 20:03 UTC, charles-cowart commented on microsetta_private_api/repo/survey_template_repo.py
> +            if cur.rowcount == 0:
Resolved. I believe this code was part of a commented out check that was removed.

2022-12-09 20:05 UTC, charles-cowart commented on microsetta_private_api/repo/survey_template_repo.py
> +                response_type = row[4]
Similar as the previous example. The SELECT * is really just a wrapper for the UNIONed queries inside, which explicitly define the parameters and their order. The enclosing SELECT is just to order them by creation time and survey question id.

2022-12-09 22:02 UTC, charles-cowart commented on microsetta_private_api/repo/survey_template_repo.py
> +            raise ValueError("survey_ids is not a list of survey ids")
Removed. Examined the callers and can pretty safely say only the correct types will be sent.

2022-12-09 22:02 UTC, charles-cowart commented on microsetta_private_api/repo/survey_template_repo.py
> +        if len(survey_ids) == 0 or '' in survey_ids or None in survey_ids:
Removed. Examined the callers and can pretty safely say only the correct types will be sent.

2022-12-09 22:51 UTC, charles-cowart commented on microsetta_private_api/repo/survey_template_repo.py
> +                # If survey_id isn't a valid UUID, a ValueError will be
Resolved.

2022-12-09 22:52 UTC, charles-cowart commented on microsetta_private_api/repo/survey_template_repo.py
> +    def _remote_survey_template_id_from_survey_id(self, survey_id):
Resolved. These were reworked from legacy functions before we included the survey_template_id column in ag_login_surveys table. Both of these were removed and the calling method just makes a simple query.

2022-12-09 22:52 UTC, charles-cowart commented on microsetta_private_api/repo/survey_template_repo.py
> +            # note these ids are unique string ids, not integer ids.
Resolved. These were reworked from legacy functions before we included the survey_template_id column in ag_login_surveys table. Both of these were removed and the calling method just makes a simple query.

2022-12-09 23:02 UTC, charles-cowart commented on microsetta_private_api/repo/tests/test_survey_template_repo.py
> +            try:
Resolved

2022-12-09 23:03 UTC, charles-cowart commented on microsetta_private_api/repo/tests/test_survey_template_repo.py
> +                sr.create_source(HUMAN_SOURCE)
Resolved.

2022-12-09 23:04 UTC, charles-cowart commented
@cassidysymons @wasade ostensibly finished! All comments addressed.

2022-12-09 23:10 UTC, wasade commented
Thanks, reviewing in a moment

2022-12-09 23:45 UTC, wasade requested changes
Thanks Charlie. So I don't see where barcodes are correctly associated with their most temporally similar survey, and I don't see an example of producing correct metadata for a sample when a source has taken the same survey multiple times.

2022-12-09 23:45 UTC, wasade commented on microsetta_private_api/admin/tests/test_admin_api.py
> +                print("\t%s" % bar)
```suggestion
```

2022-12-09 23:45 UTC, wasade commented on microsetta_private_api/admin/tests/test_admin_api.py
> +                print("\t%s" % bar)
```suggestion
```

2022-12-09 23:45 UTC, wasade commented on microsetta_private_api/admin/tests/test_admin_api.py
Can a test be added for when a sample's source has multiple instances of the same survey template, and which demonstrates that the sample is correctly associated to right survey?

2022-12-09 23:45 UTC, wasade commented on microsetta_private_api/admin/tests/test_admin_api.py
Or is this done elsewhere?

2022-12-09 23:45 UTC, wasade commented on microsetta_private_api/api/tests/test_api.py
> +            survey_template_id=st_repo.DIET_ID,)
```suggestion
            survey_template_id=st_repo.DIET_ID)
```

2022-12-09 23:45 UTC, wasade commented on microsetta_private_api/repo/survey_template_repo.py
> +            cur.execute("""SELECT b.creation_time
This will return multiple times if the user has taken the same survey multiple times. A single value is pulled out on like 1047, and I believe that will be an arbitrary time stamp. This function appears to be used later for determining what metadata to associate to a sample, so it seems that using an arbitrary timestamp is incorrect.

2022-12-09 23:45 UTC, wasade commented on microsetta_private_api/repo/survey_template_repo.py
> +            # if a timestamp could not be found for the survey template id in
Does this scenario actually occur?

```sql
[local]:5432 dtmcdonald@ag_test=# select * from ag.ag_login_surveys where creation_time is null;
+-------------+-----------+------------------+-----------+---------------+
| ag_login_id | survey_id | vioscreen_status | source_id | creation_time |
+-------------+-----------+------------------+-----------+---------------+
+-------------+-----------+------------------+-----------+---------------+
(0 rows)

```

2022-12-09 23:45 UTC, wasade commented on microsetta_private_api/repo/survey_template_repo.py
> +            raise ValueError("A timestamp could not be found for barcode "
Let's issue an `ALTER TABLE` on `ag_login_surveys` and enforce that `creation_time` is `NOT NULL`.

2022-12-09 23:45 UTC, wasade commented on microsetta_private_api/repo/survey_template_repo.py
> +            # retrieve the timestamp used to prefer one response over another.
The called function does not determine what the most temporally similar survey timestamp is to the barcode timestamp.

2022-12-09 23:45 UTC, wasade commented on microsetta_private_api/repo/survey_template_repo.py
> +            for row in rows:
Can the tuple be expanded to avoid magic numbers?

2022-12-09 23:45 UTC, wasade commented on microsetta_private_api/repo/survey_template_repo.py
> +                    results[question_id] = response
I believe this complex logic is done twice, can it be decomposed?

2022-12-09 23:45 UTC, wasade commented on microsetta_private_api/repo/tests/test_survey_template_repo.py
> +            # disabled because some other tests rely on an invalid id.
I'm not sure I understand, is it correct that this test is commented out?

2022-12-09 23:45 UTC, wasade commented on microsetta_private_api/repo/tests/test_survey_template_repo.py
> +            print("SOURCE ID: %s" % source_id)
```suggestion
```

2022-12-12 18:35 UTC, charles-cowart commented on microsetta_private_api/admin/tests/test_admin_api.py
> +                print("\t%s" % bar)
ty for the catch!

2022-12-12 18:48 UTC, charles-cowart commented
> Thanks Charlie. So I don't see where barcodes are correctly associated with their most temporally similar survey...

Hi @wasade Thanks for the review! I have a method called _get_timestamp() that looks for a survey that is an exact match to a barcode and a survey template id. If it finds one, it'll return that to the code I've highlighted below. If for some reason it can't find a matching survey, it'll assume every source has a creation timestamp and return that instead. It's in a separate method so we could easily tweak it based on your expected feedback.

The code below will take the set of all responses across all times and return them to the caller. (Not sure if that's what we really wanted because some answers change over time and some don't.) Where there are multiple responses to the same question, it will select the response closest to the timestamp returned by _get_timestamp():

https://github.com/charles-cowart/microsetta-private-api/blob/eda55696ea443ff5edd21dcd6e4a93260f99536e/microsetta_private_api/repo/survey_template_repo.py#L1141-L1154.

2022-12-12 18:56 UTC, charles-cowart commented on microsetta_private_api/repo/tests/test_survey_template_repo.py
> +            # disabled because some other tests rely on an invalid id.
That is correct. I added a check to migrate_responses() to ensure the source_id is a valid one, but it causes a few of the other tests to fail because they use a mocked source_id ('aaaa-fffff...'). I commented it out but left it here for discussion. I didn't want to try to mock the check for the other tests at that point. I think actually it can be removed because we assume other parameters to functions and methods like these are supplying only valid parameters.

2022-12-12 19:06 UTC, charles-cowart commented on microsetta_private_api/repo/survey_template_repo.py
> +                    results[question_id] = response
Sure I'll take a look.

2022-12-12 19:09 UTC, charles-cowart commented on microsetta_private_api/repo/survey_template_repo.py
> +            for row in rows:
Ah I see what you're saying - no problem, that should work...

2022-12-12 19:11 UTC, charles-cowart commented on microsetta_private_api/repo/survey_template_repo.py
> +            # retrieve the timestamp used to prefer one response over another.
Ah, gotcha - there is a timestamp for the barcode - it's in barcodes.barcode. You mean that one right?

2022-12-12 19:12 UTC, charles-cowart commented on microsetta_private_api/repo/survey_template_repo.py
> +            # if a timestamp could not be found for the survey template id in
Not in the test data, but I'm not sure what staging and production look like so I was coding a little defensively.

2022-12-12 19:15 UTC, cassidysymons commented on microsetta_private_api/repo/survey_template_repo.py
> +            # if a timestamp could not be found for the survey template id in
The query @wasade ran was on Staging, which contains a snapshot of our production database. If we add the NOT NULL constraint as suggested, we can safely assume that the scenario won't occur.

2022-12-12 19:15 UTC, charles-cowart commented on microsetta_private_api/repo/survey_template_repo.py
> +            cur.execute("""SELECT b.creation_time
Ty, yeah I address that in the comment beginning on L1044. I figured I would get reviewer input on that.

2022-12-12 19:18 UTC, charles-cowart commented on microsetta_private_api/admin/tests/test_admin_api.py
It's definitely a case I considered when writing the tests for it, so there isn't a specific test for it. I'll go through the modified and new tests and see if I can pick out the examples of doing this and see if you think it tests it well enough. I have a feeling some of those tests will need to be modified after looking at the other comments anyway.

2022-12-12 19:23 UTC, charles-cowart commented on microsetta_private_api/repo/survey_template_repo.py
> +            # if a timestamp could not be found for the survey template id in
That sounds great thanks!

2022-12-12 19:40 UTC, wasade commented on microsetta_private_api/repo/survey_template_repo.py
> +            # retrieve the timestamp used to prefer one response over another.
No, the timestamp is `ag.ag_kit_barcodes.sample_{date,time}`

2022-12-12 19:41 UTC, wasade commented on microsetta_private_api/repo/survey_template_repo.py
> +            # if a timestamp could not be found for the survey template id in
I actually ran it locally, but just verified it on staging

2022-12-12 19:45 UTC, wasade commented
Thanks, @charles-cowart. `_get_timestamp` does not interact with `ag_kit_barcodes` as far as I can tell, so it is not obtaining the sample's timestamp

2022-12-12 19:53 UTC, charles-cowart commented on microsetta_private_api/repo/survey_template_repo.py
> +            raise ValueError("A timestamp could not be found for barcode "
Sounds good! Resolved.

2022-12-12 20:04 UTC, charles-cowart commented on microsetta_private_api/repo/survey_template_repo.py
> +            # retrieve the timestamp used to prefer one response over another.
@wasade It looks like these columns are mostly NULL for local data at least, is it okay to assume that for our use case at least, we'll always have one? Maybe this is the timestamp you were referring to when you said there was some legacy ids w/out timestamps?

2022-12-12 20:08 UTC, wasade commented on microsetta_private_api/repo/survey_template_repo.py
> +            # retrieve the timestamp used to prefer one response over another.
NULL for unassigned samples, not null for samples assocaited with a source

2022-12-12 20:14 UTC, charles-cowart commented on microsetta_private_api/repo/survey_template_repo.py
> +            for row in rows:
Resolved.

2022-12-12 21:20 UTC, charles-cowart commented on microsetta_private_api/repo/tests/test_survey_template_repo.py
> +            # disabled because some other tests rely on an invalid id.
Removed.

2022-12-12 21:20 UTC, charles-cowart commented on microsetta_private_api/repo/survey_template_repo.py
> +                    results[question_id] = response
Resolved.

2022-12-12 22:13 UTC, charles-cowart commented on microsetta_private_api/repo/survey_template_repo.py
> +            # retrieve the timestamp used to prefer one response over another.
tentatively resolved.

2022-12-13 01:31 UTC, charles-cowart commented on microsetta_private_api/repo/survey_template_repo.py
> +            # retrieve the timestamp used to prefer one response over another.
Updated to remove survey_template_ids as part of the query. It's not really needed since all timestamps would be the same in any case, and even if there were multiple surveys of the type requested or none, we'd want to center our responses around the barcode's timestamp.

2022-12-13 01:33 UTC, charles-cowart commented on microsetta_private_api/repo/survey_template_repo.py
> +            cur.execute("""SELECT b.creation_time
Resolved. Replaced with a new query based on barcode timestamp found in ag.ag_kit_barcodes.

2022-12-13 01:36 UTC, charles-cowart commented on microsetta_private_api/repo/survey_template_repo.py
> +            # what if there are multiple template Xs? Should we take the
Resolved. Replaced with a new query based on barcode timestamp found in ag.ag_kit_barcodes.

2022-12-13 01:47 UTC, cassidysymons commented on microsetta_private_api/repo/survey_template_repo.py
> +            # Expect that one and only one result will always be found.
Given that we're changing the system to allow people to re-take surveys, that's not a safe assumption moving forward. I know my earlier comment reflected that it was a safe assumption for old data, but we either need this function to account for multiple records, or one of the upstream functions to do so.

2022-12-13 02:00 UTC, charles-cowart commented
I resolved the merge conflict with the idea that I didn't change anything substantial to the vioscreen-related method and hence the changes in master-overhaul superseded them.

2022-12-13 02:31 UTC, charles-cowart commented
Reviewing and resolving test errors post merge.

2022-12-13 05:21 UTC, charles-cowart commented on microsetta_private_api/admin/tests/test_admin_api.py
I would say this case is covered in test_migrate_responses_by_barcode():
https://github.com/biocore/microsetta-private-api/blob/0ebec2c0470aa9189c7e774ce1b54d0f37f1bdcf/microsetta_private_api/repo/tests/test_survey_template_repo.py#L697-L720

We have an existing filled survey of template type 1 and then submit two filled surveys of template type 10. Each survey has their own answer for '111/Birth Month'. The correct answer for retrieving by barcode would be to return the earliest value from template 1 (the one closest to the barcode's timestamp) (June) instead of the later values from the template 10s (February, March).

I could piggy-back a template 10-only value - probably GENDER_v2/502 since it's also a SINGLE, but I don't think it's needed. The first submission could submit "Male" and the second submission could submit "Female" and we would test to see that "Male" was returned (since it would be from a survey closer in time to the barcode timestamp than the one after) (or vice-versa).

2022-12-13 05:26 UTC, charles-cowart commented on microsetta_private_api/repo/survey_template_repo.py
> +            # Expect that one and only one result will always be found.
I think this is okay now, because the query has been changed per Daniel's request to use the sample_date and sample_time columns from ag.ag_kit_barcodes. In this case, there really will be only one timestamp, as this is the one associated with the barcode itself, instead of one of potentially many surveys.

2022-12-13 05:27 UTC, charles-cowart commented
@cassidysymons @wasade Hi guys - I think responding to those two open questions makes this tentatively resolved again. All other comments have been resolved. Please let me know what you think. Best, C

2022-12-13 05:30 UTC, cassidysymons commented on microsetta_private_api/admin/tests/test_admin_api.py
That test isn't accurately exercising the right logic. If you look at how ag.source_barcodes_surveys functions and is populated, it essentially grabs everything from ag.ag_login_surveys at the time that a user finishes claiming a sample. The above test wouldn't exercise that logic, as it's not going to populate ag.source_barcodes_surveys with the new surveys being taken.

2022-12-13 06:32 UTC, charles-cowart commented on microsetta_private_api/admin/tests/test_admin_api.py
Hmm, I made a point to display the SQL statements being generated and reviewed them during development, so it's a little surprising that something is amiss. I will dig into it first thing in the morning.

2022-12-21 00:21 UTC, cassidysymons commented
@wasade When you have a moment, can you please give this a look and see if there are any unresolved issues or further changes you think would be valuable?

2022-12-21 00:45 UTC, wasade approved these changes
I think this is okay from a static analysis.

2022-12-21 00:46 UTC, wasade commented
@cassidysymons I recommend squash and merge given the number of commits

2022-12-21 00:54 UTC, merged