Overhaul
biocore/microsetta-private-api pull request #502
Opened 2023-02-01 19:10 UTC by cassidysymons

Draft, not ready for review

2023-02-08 06:03 UTC, wasade requested changes
Not listed in the comments, it looks like tests for the following are needed:

* Test for “generate_ffq_codes”
* Test for “create_ffq_code”
* Test for "_get_supplied_kit_id_by_sample"
* Test for "get_latest_signed_consent"
* Test for "get_registry_entries_by_source"
* Test for "get_unused_code"
* Test for “get_signed_consents”

2023-02-08 22:13 UTC, sejsong commented on microsetta_private_api/db/patches/0113.sql
> +  You will sample yourself using the kit that was provided to you.  Instructions are included in the kit so you know what to do.  The most common sample is of your poop (stool) where you apply a smal
I think this is language from the adolescent consent, which we didn't really change from what it said before. In any case, I don't think this needs to change, since these aren't meant to be the full instructions anyway, as those would be provided in the kit itself, in a separate document, or by the study coordinators.

2023-02-08 22:18 UTC, sejsong commented on microsetta_private_api/db/patches/0113.sql
> +  You do not have to participate. Your participation in this study is completely voluntary and you can refuse to participate or withdraw at any time by withdrawing your consent and deleting your onli
That sentence isn't meant to mean after they've withdrawn, since we won't know how to contact them at that point anyway. It's a statement that is recommended by the IRB to include for this section, and I think as written, it seems clear to me that it's for alerting them while they're still a part of the study, not after they've withdrawn.

2023-02-08 22:19 UTC, sejsong commented on microsetta_private_api/db/patches/0113.sql
> +-- Adjust various questions
We ran all of these changes by Allyssa, and she indicated that minor revisions to wording that does not affect their meaning, and changes to placement of questions do not require IRB review.

2023-02-08 22:23 UTC, sejsong commented on microsetta_private_api/db/patches/0113.sql
> +  The research team will store and process your Personal Data at our research site in the United States. The United States does not have the same laws to protect your Personal Data as countries in th
I think we could reference the privacy statement in this section of the consent so they can see all the details. We can change the following statement "Additional information about the protections we will use is included in this consent document." to "Additional information about the protections we will use is included in our Privacy Statement."

Good catch on 'Study Data'. We should change that to 'Personal Data'.

2023-02-09 00:25 UTC, wasade commented on microsetta_private_api/db/patches/0113.sql
> +  You do not have to participate. Your participation in this study is completely voluntary and you can refuse to participate or withdraw at any time by withdrawing your consent and deleting your onli
I inquired with Gail for a second opinion and she too thought this implied we may inform people after they have withdrawn. 

The issue isn't the sentence itself, but that it falls immediately after describing withdrawal

2023-02-09 21:06 UTC, sejsong commented on microsetta_private_api/db/patches/0113.sql
> +  You do not have to participate. Your participation in this study is completely voluntary and you can refuse to participate or withdraw at any time by withdrawing your consent and deleting your onli
I don't think it makes sense to move it up to the beginning of the section. In the template that the IRB provided, there is a break between the withdrawal description and this sentence. Do you think adding that break here will help with the clarification?

2023-02-09 21:12 UTC, wasade commented on microsetta_private_api/db/patches/0113.sql
> +  You do not have to participate. Your participation in this study is completely voluntary and you can refuse to participate or withdraw at any time by withdrawing your consent and deleting your onli
A line break? Ya I think that would help. What do you think about having it come before the handful of sentences on withdrawal?

2023-02-09 23:04 UTC, wasade commented on microsetta_private_api/db/patches/0113.sql
> +  You do not have to participate. Your participation in this study is completely voluntary and you can refuse to participate or withdraw at any time by withdrawing your consent and deleting your onli
perfect!

2023-02-14 17:15 UTC, cassidysymons commented on microsetta_private_api/repo/survey_template_repo.py
> +            gender = results.get('GENDER_v2')
The new gender question carries a different meaning - biological sex at birth - which is the reason we're creating a new question in the database. As such, migrating old responses would be inappropriate.

2023-02-14 17:20 UTC, cassidysymons commented on microsetta_private_api/translations/es_ES/LC_MESSAGES/messages.po
> +msgstr ""
Per explanation on leadership call, Japanese translations will be added and vetted in a separate pull request.

2023-02-14 17:20 UTC, cassidysymons commented on microsetta_private_api/translations/ja_JP/LC_MESSAGES/messages.po
> +msgstr ""
Per explanation on leadership call, Japanese translations will be added and vetted in a separate pull request.

2023-02-14 17:37 UTC, cassidysymons commented on microsetta_private_api/repo/consent_repo.py
> +                if parent_1 is None:
parent_2 no longer appears on the form, so no, it's not possible for parent_2 to have a value

2023-02-14 18:17 UTC, cassidysymons commented on microsetta_private_api/db/patches/0113.sql
> +-- Add an Address 2 field to the account table
No, 0112.sql already exists in master and has subsequently been merged into master-overhaul, it was the patch that fixed state on an account that couldn't be deleted (https://github.com/biocore/microsetta-private-api/pull/498).

When we eventually deploy the overhaul Private API into production, we will need to set the current patch back to 0105.sql. This causes patch 0112.sql to be reapplied, but it doesn't produce an error or break state.

2023-02-14 18:17 UTC, cassidysymons commented on microsetta_private_api/db/patches/0113.sql
> +INSERT INTO ag.survey_response (american) VALUES ('N/A');
Per discussion, this will be handled in a separate pull request.

2023-02-14 18:20 UTC, cassidysymons commented on microsetta_private_api/celery_utils.py
> +        # "poll_daklapack_orders": {
It has been tested in staging and is unchanged since then. All of the perk fulfillment code will receive a final round of testing on Staging, they're disabled right now while the focus is on the UI changes. The primary reason for this is that the test order Andy placed against Staging - and that we fulfilled - no longer exists in the Staging database due to state changes. It would be valuable to test the actual fulfillment one more time before going into production, but in the interest of not having the order re-fulfilled every time we drop and reload the staging DB, I have the perk fulfillment tasks turned off.

2023-02-14 18:21 UTC, cassidysymons commented on microsetta_private_api/db/patches/0113.sql
> +    (511, 'Unspecified', 0),
Per discussion, this will be handled in a separate pull request.

2023-02-14 18:22 UTC, cassidysymons commented on microsetta_private_api/db/patches/0113.sql
> +UPDATE ag.survey_question_response SET display_index = 3 WHERE survey_question_id = 38 AND response = 'I tend to have diarrhea (watery stool) - Type 5, 6 and 7';
There's a unique constraint on the display_index column and the entries needed to be reordered, so the choices were either to drop and re-enable the constraint, or play musical chairs with the entries. I'll add a comment reflecting that.

2023-02-14 18:25 UTC, cassidysymons commented on microsetta_private_api/db/patches/0113.sql
> +-- Set the CSS classes for questions
From my standpoint, the fact that private-api generates the Vue model makes it the pragmatic choice. There needs to be a link between a given survey_question_id and the CSS classes we're associating with it. Moving that into interface would require an even clunkier and more static solution.

2023-02-14 19:36 UTC, cassidysymons commented on microsetta_private_api/api/microsetta_private_api.yaml
> +          $ref: '#/components/responses/403Forbidden'
No, it returns an empty list

2023-02-16 17:22 UTC, wasade commented on microsetta_private_api/celery_utils.py
> +        # "poll_daklapack_orders": {
Thanks

2023-02-16 17:22 UTC, wasade commented on microsetta_private_api/db/patches/0113.sql
> +INSERT INTO ag.survey_response (american) VALUES ('N/A');
Thanks

2023-02-16 17:23 UTC, wasade commented on microsetta_private_api/db/patches/0113.sql
> +    (511, 'Unspecified', 0),
Thanks

2023-02-16 17:33 UTC, wasade commented on microsetta_private_api/db/patches/0113.sql
> +-- Add an Address 2 field to the account table
Thanks

2023-02-16 17:33 UTC, wasade commented on microsetta_private_api/db/patches/0113.sql
> +-- Set the CSS classes for questions
Agree

2023-02-16 17:35 UTC, wasade commented on microsetta_private_api/db/patches/0113.sql
> +UPDATE ag.survey_question_response SET display_index = 3 WHERE survey_question_id = 38 AND response = 'I tend to have diarrhea (watery stool) - Type 5, 6 and 7';
Makes sense, thanks

2023-02-16 17:38 UTC, wasade commented on microsetta_private_api/db/patches/0113.sql
> +  There is no direct benefit to you for participating in this study. You will get access to your data that will give you and your parents an idea of what is in your sample and how it compares with ot
cc @sejsong, when you have a moment could you resolve this conversation?

2023-02-16 17:38 UTC, wasade commented on microsetta_private_api/db/patches/0113.sql
> +  Biospecimens (such as stool, skin, urine, or blood) collected from you for this study and information obtained from your biospecimens may be used in this research or other research, and shared with
@sejsong, is this resolved?

2023-02-16 17:38 UTC, wasade commented on microsetta_private_api/db/patches/0113.sql
> +  The purpose of this study is to assess more accurately the microbial differences among people and whether these differences can be attributed to factors such as lifestyle, diet, body type, age or t
@sejsong, is this resolved?

2023-02-16 17:38 UTC, wasade commented on microsetta_private_api/db/patches/0113.sql
> +  Once your sample has been analyzed, we will upload results to your account and send you an email with a link to log in and view them.  We estimate that it can take 1-3 months for you to learn the r
@sejsong, is this resolved?

2023-02-16 17:39 UTC, wasade commented on microsetta_private_api/db/patches/0113.sql
> +  Biospecimens (such as stool, skin, urine, or blood) collected from you for this study and information obtained from your biospecimens may be used in this research or other research, and shared with
@sejsong, is this resolved?

2023-02-16 17:39 UTC, wasade commented on microsetta_private_api/db/patches/0113.sql
> +  Federal and State laws generally make it illegal for health insurance companies, group health plans, and most employers to discriminate against you based on your genetic information. This law gener
I think this one is resolved so closing

2023-02-16 17:39 UTC, wasade commented on microsetta_private_api/db/patches/0113.sql
> +  Dr. Rob Knight and his research team are doing a research study to find out more about the trillions of tiny living things like bacteria and viruses that live in you or on you. These tiny things ar
@sejsong, is this resolved?

2023-02-16 17:39 UTC, wasade commented on microsetta_private_api/db/patches/0113.sql
> +  There may be costs associated with obtaining a kit but there will be no cost for participating in the sampling procedure.
@sejsong, is this resolved?

2023-02-16 17:40 UTC, wasade commented on microsetta_private_api/db/patches/0113.sql
> +  <strong>University of California, San Diego<br />
@sejsong, is this resolved?

2023-02-16 17:40 UTC, wasade commented on microsetta_private_api/db/patches/0113.sql
> +  <strong>University of California, San Diego<br />
@sejsong, is this resolved?

2023-02-16 17:40 UTC, wasade commented on microsetta_private_api/db/patches/0113.sql
> +  <strong>University of California, San Diego<br />
@sejsong, is this resolved?

2023-02-16 17:40 UTC, wasade commented on microsetta_private_api/db/patches/0113.sql
> +  The Microsetta Initiative
@sejsong, is this resolved?

2023-02-16 17:40 UTC, wasade commented on microsetta_private_api/db/patches/0113.sql
> +  <strong>University of California, San Diego<br />
@sejsong, is this resolved?

2023-02-16 17:41 UTC, wasade commented on microsetta_private_api/db/patches/0113.sql
> +  <strong>The Microsetta Initiative<br />
@sejsong, is this resolved?

2023-02-16 17:41 UTC, wasade commented on microsetta_private_api/db/patches/0113.sql
> +  There is no direct benefit to you for participating in this study. You will get access to your data that will give you and your parents an idea of what is in your sample and how it compares with ot
@sejsong, is this resolved?

2023-02-16 17:57 UTC, wasade commented on microsetta_private_api/repo/consent_repo.py
> +                if parent_1 is None:
In verifying this against the database, it does appear to be the case that there are no instances of `parent_1_name is null and parent_2_name is not null`. However, in checking this I noticed that consent information from `ag.source` has not been migrated into `ag.consent_audit`. At the moment, we currently maintain consent information in two locations.

2023-02-16 18:14 UTC, wasade commented on microsetta_private_api/repo/survey_template_repo.py
> +            gender = results.get('GENDER_v2')
That holds as long as this function is only ever called in association to new surveys, which I don't believe is guaranteed. Can't a historical user, who hasn't yet taken an FFQ, take one and in which case the the `GENDER` variable should be obtained? Outside of the current intended use, this would lead to a bug should this function be reused in the future. What about prioritizing `GENDER_v2` if it exists and fallback to `GENDER` otherwise?

2023-02-17 22:08 UTC, cassidysymons commented on microsetta_private_api/repo/consent_repo.py
> +                if parent_1 is None:
To migrate existing users' consents into `ag.consent_audit`, we would need to create copies of the consent documents they signed in `ag.consent_documents` which isn't a huge task in and of itself. However, to ensure the data is an accurate reflection of what they actually signed, we would need to go back through commit histories to determine when/if any of the consent documents have been edited - and more importantly, deployed, since that would reflect which version a user actually saw - create a database entry for each, and migrate all existing consents. While theoretically possible, it would be both labor-intensive and likely prone to errors.

2023-02-17 23:42 UTC, wasade commented on microsetta_private_api/repo/consent_repo.py
> +                if parent_1 is None:
What happens if a user who signed a historical consent uses the "Consent Documents" UI?

2023-02-21 19:10 UTC, cassidysymons commented on microsetta_private_api/repo/consent_repo.py
> +                if parent_1 is None:
At the moment, it would throw an error if they hadn't signed an updated data consent, which is obviously not ideal. Off the top of my head, we could either hide that feature entirely for people who have not re-consented or, when they click on it, display a message encouraging the user to re-consent with the newest documents. I'll consult with the UI team on our call in a bit as to the best course of action, but I think any change in that regard would fall into the Interface PR.

2023-02-21 21:31 UTC, cassidysymons commented on microsetta_private_api/repo/consent_repo.py
> +                if parent_1 is None:
Following up after UI meeting - for historical accounts, clicking Consent Documents will display verbiage encouraging them to re-consent to the new documents. No changes to Private API are needed to support that, so I believe that closes out this PR.

2023-02-21 23:00 UTC, cassidysymons commented on microsetta_private_api/repo/consent_repo.py
> +                if parent_1 is None:
@wasade Per the discussion we had on this afternoon's developer's call, I looked at the source scrubbing code and have a few items:
1) The scrub function that we looked at when you shared your screen - `ConsentRepo.scrub` - is only responsible for the `ag.consent_audit` table by design. This scrub function is invoked by `scrub_source()` in `_source.py`, which also invokes the `SourceRepo.scrub` function, cleaning up the consent-related fields that exist in `ag.source`. Conceptually, that's somewhat frustrating. But structurally, this makes sense, as the `SourceRepo` should be responsible for what's in `ag.source`, and the `ag.consent_audit` table falls within the scope of `ConsentRepo`.
2) However, `ag.consent_audit` should be updated to include a `date_revoked` field, which the `ConsentRepo.scrub` function needs to handle.
3) At the moment, we have both a `delete_source` and `scrub_source` function `_source.py`. I think we had briefly discussed this in the past, but I'm unsure if we came to a conclusion - are you opposed to eliminating the idea of outright deleting sources (e.g. `DELETE FROM ag.source`) in favor of scrubbing? I'd like to clean that up while I have the scrub code in front of me, and scrubbing generally seems safer than deleting.

2023-02-21 23:45 UTC, wasade commented on microsetta_private_api/repo/consent_repo.py
> +                if parent_1 is None:
Thanks! All sounds good. I think scrubbing all rather than allowing for delete would reduce complexity. The cases where a delete would be allowed are pretty thin I think as its limited to no FFQ and no associated samples

2023-02-22 02:11 UTC, cassidysymons commented on microsetta_private_api/repo/consent_repo.py
> +                if parent_1 is None:
Changes for this are done, so this PR is ready for re-review.

2023-02-22 17:36 UTC, wasade approved these changes

2023-02-22 17:44 UTC, merged