Updates for Spanish (es_MX & es_ES)
biocore/microsetta-private-api pull request #509
Opened 2023-02-28 20:35 UTC by cassidysymons

WIP - Deploying to Staging for Alejandra to review new translations in context and opening PR to confirm no Lint/test issues. Will update PR and mark for review once it's ready.

2023-03-09 17:25 UTC, cassidysymons commented
@wasade FYI, the code that's reflected in this PR and https://github.com/biocore/microsetta-interface/pull/274 is running on staging

2023-03-20 16:23 UTC, wasade requested changes
Just a few minor comments, thanks!

2023-03-20 16:23 UTC, wasade commented on microsetta_private_api/repo/survey_template_repo.py
> +        }
```suggestion
        }
        
        if language_tag is not in tag_to_col:
            raise RepoException(f"{language_tag} is not supported.")
            
```

2023-03-20 16:23 UTC, wasade commented on microsetta_private_api/repo/survey_template_repo.py
> +        }
```suggestion
        }
        
        if language_tag is not in tag_to_col:
            raise RepoException(f"{language_tag} is not supported.")
            
```

2023-03-20 16:23 UTC, wasade commented on microsetta_private_api/db/patches/0115.sql
> +-- Standardize the frequency-oriented questions to the legacy responses. The new, shorter responses have not actually been used so it's safe to change them.
I believe this change set will necessitate a full reload of the Qiita metadata

2023-03-20 16:23 UTC, wasade commented on microsetta_private_api/repo/tests/test_survey_template_repo.py
Can a minor test be added to assert behavior of an unexpected language tag? something like

```python
    def test_migrate_response_unexpected_language_tag(self):
        with Transaction() as t:
            with t.cursor() as cur:
                # get source_id associated with survey_id 6d16832b84358c93 as
                # it is randomly generated each install.
                cur.execute("SELECT source_id FROM ag_login_surveys WHERE "
                            "survey_id = '6d16832b84358c93'")
                source_id = cur.fetchone()[0]

            str = SurveyTemplateRepo(t)
            with self.assertRaises(RepoException):
                str.migrate_responses(source_id, 19, "foo_bar")
```

2023-03-20 16:28 UTC, cassidysymons commented on microsetta_private_api/db/patches/0115.sql
> +-- Standardize the frequency-oriented questions to the legacy responses. The new, shorter responses have not actually been used so it's safe to change them.
The queries in this block only alter new responses that have never been used in the production environment. When they were added to the database, the responses were slightly different as the desired verbiage is more concise - I'm just updating them to match the frequencies that have traditionally been used. Since it's not touching any existing survey responses, would it still necessitate a full reload of Qiita?

2023-06-04 23:15 UTC, cassidysymons commented on microsetta_private_api/repo/survey_template_repo.py
> +        }
It looks like the `get_survey_template` function was already raising a `NotFound` exception for an invalid `language_tag`, so I used the same exception or all other functions that were converting `language_tag` to column name for the sake of consistency.

2023-06-04 23:15 UTC, cassidysymons commented on microsetta_private_api/repo/survey_template_repo.py
> +        }
It looks like the `get_survey_template` function was already raising a `NotFound` exception for an invalid `language_tag`, so I used the same exception or all other functions that were converting `language_tag` to column name for the sake of consistency.

2023-06-06 21:18 UTC, wasade commented on microsetta_private_api/db/patches/0115.sql
> +    Puede negarse a que su hijo participe o retirar a su hijo en cualquier momento eliminando el perfil en línea de su hijo, o solicitando la eliminación de su cuenta.. Nuestros investigadores seguir
There's a double period here after "cuenta"

2023-06-06 21:19 UTC, wasade commented on microsetta_private_api/db/patches/0115.sql
> +    Puede negarse a que su hijo participe o retirar a su hijo en cualquier momento eliminando el perfil en línea de su hijo, o solicitando la eliminación de su cuenta.. Nuestros investigadores seguir
There's a double period after "cuenta". For some reason github is not allowing a suggestion code change

2023-06-06 21:19 UTC, wasade commented on microsetta_private_api/db/patches/0115.sql
> +    Puede negarse a que su hijo participe o retirar a su hijo en cualquier momento eliminando el perfil en línea de su hijo, o solicitando la eliminación de su cuenta.. Nuestros investigadores seguir
Same here

2023-06-06 21:20 UTC, wasade commented
Just two minor items, thanks!

2023-06-08 15:58 UTC, cassidysymons commented
@wasade Good catch, thanks! Fixed so this should be good once workflow finishes.

2023-06-08 16:44 UTC, merged

2023-06-08 16:44 UTC, wasade commented
Thanks!!