Adjustments to Metadata Push
biocore/microsetta-private-api pull request #517
Opened 2023-05-15 04:27 UTC by cassidysymons

2023-05-17 20:38 UTC, wasade requested changes
Thanks, @cassidysymons! I think this is largely good and very clean. The general suggestions are to be make some adjustments to be a little more defensive

2023-05-17 20:38 UTC, wasade commented on microsetta_private_api/api/_account.py
> +    account_obj.cannot_geocode = cannot_geocode
Could this logic be moved to after a successful account creation? No need to geocode if they don't have a valid account, right?

2023-05-17 20:38 UTC, wasade commented on microsetta_private_api/repo/google_geocoding_repo.py
> +        Create a record before pinging Google so we have visibility into
I think this may be copypasta

2023-05-17 20:38 UTC, wasade commented on microsetta_private_api/repo/google_geocoding_repo.py
> +        Parameters
```suggestion
        
        Parameters
```

2023-05-17 20:38 UTC, wasade commented on microsetta_private_api/db/patches/0116.sql
> +    request_address VARCHAR NOT NULL,
Can a unique constraint be added?

2023-05-17 20:38 UTC, wasade commented on microsetta_private_api/util/google_geocoding.py
> +            geocoding_response = gg_repo.get_record(existing_request_id)
This is potentially sensitive to a race and could benefit from a lock. What if it was `get_or_create_record` and it managed its lock as needed? It would remove the need to call `check_duplicate`. The return could be `(request_id, is_new)` or something

2023-05-17 20:38 UTC, wasade commented on microsetta_private_api/util/google_geocoding.py
> +            return _parse_response(response_obj)
Erroring on the side of caution, I think this should be done in a `try/except` prior to the `.commit`

2023-05-17 20:38 UTC, wasade commented on microsetta_private_api/util/tests/test_google_geocoding.py
> +    @skipIf(SERVER_CONFIG['google_geocoding_key'] in
Could a key be added to our github secrets?

2023-05-22 16:08 UTC, wasade commented
:+1:

2023-06-15 21:42 UTC, wasade reviewed
I think just minor stuff

2023-06-15 21:42 UTC, wasade commented on microsetta_private_api/repo/metadata_repo/_repo.py
> +        longitude = "{:.2f}".format(metadata['account'].longitude)
I _think_ we need to be more coarse grained, see [USGS](https://www.usgs.gov/faqs/how-much-distance-does-a-degree-minute-and-second-cover-your-maps). This would put is I think somewhere in the range of < square mile of resolution 

cc @sejsong

2023-06-15 21:42 UTC, wasade commented on microsetta_private_api/util/google_geocoding.py
> +        if new_request is False:
```suggestion
        if not new_request:
```

2023-06-15 21:42 UTC, wasade commented on microsetta_private_api/util/google_geocoding.py
> +            t.commit()
```suggestion
                t.rollback()
            else:
                t.commit()
```

2023-06-15 21:42 UTC, wasade commented on microsetta_private_api/util/google_geocoding.py
> +        request_address += ", " + address.state
If `state` isnt' there for whatever reason, this would mean the `', '` is not added. Would that be bad?

2023-06-15 21:42 UTC, wasade commented on microsetta_private_api/util/google_geocoding.py
> +            latitude = result['geometry']['location']['lat']
There is a lot of trust here. But, I think for now let's trust google and if something breaks we should get an ugly traceback. And if this hasn't broken with our current set of accounts, then it's _probably_ fine...

2023-06-15 21:42 UTC, wasade commented on microsetta_private_api/db/patches/0116.sql
> +    INNER JOIN barcodes.barcode
nifty, I see what you did here

2023-06-16 04:17 UTC, sejsong commented on microsetta_private_api/repo/metadata_repo/_repo.py
> +        longitude = "{:.2f}".format(metadata['account'].longitude)
Is this supposed to specify midpoint of the geo_loc_name or is it really based on the exact address? If the former, it doesn't matter as much, but I think we should probably still use nearest degree, not to 2 decimals. If the latter, then we definitely need to go coarser.

2023-06-16 04:21 UTC, cassidysymons commented on microsetta_private_api/repo/metadata_repo/_repo.py
> +        longitude = "{:.2f}".format(metadata['account'].longitude)
The lat and long are derived directly from the address via Google's Geocoding API. Do you want it adjusted to whole degrees or one decimal place?

2023-06-16 04:28 UTC, sejsong commented on microsetta_private_api/repo/metadata_repo/_repo.py
> +        longitude = "{:.2f}".format(metadata['account'].longitude)
whole degrees

2023-06-16 04:43 UTC, cassidysymons commented on microsetta_private_api/repo/google_geocoding_repo.py
> +        record's response_body. If it does not, create a record and return the
It's the JSON object that Google's Geocoding API returns.

2023-06-16 04:44 UTC, cassidysymons commented on microsetta_private_api/repo/google_geocoding_repo.py
> +        geocoding_request_id : uuid4 or response_body : json
Refactoring it was pretty quick, so it now has a consistent return type.

2023-06-16 04:50 UTC, cassidysymons commented on microsetta_private_api/util/google_geocoding.py
> +        request_address += ", " + address.state
Not really. Google's API is pretty intelligent about parsing addresses even when improperly formatted, we're just providing as much as clarity as possible when the values do exist.

2023-06-16 04:56 UTC, cassidysymons commented on microsetta_private_api/repo/metadata_repo/_repo.py
> +        longitude = "{:.2f}".format(metadata['account'].longitude)
Code adjusted accordingly. I'll kick off another run on staging so we can reload Qiita RC in the morning.

2023-06-16 15:09 UTC, wasade commented on microsetta_private_api/repo/google_geocoding_repo.py
> +        geocoding_request_id : uuid4 or response_body : json
Oh cool, thanks!

2023-06-16 15:10 UTC, wasade commented on microsetta_private_api/repo/google_geocoding_repo.py
> +        record's response_body. If it does not, create a record and return the
I see

2023-06-16 15:14 UTC, wasade requested changes
All in suggested changes

2023-06-16 15:14 UTC, wasade commented on microsetta_private_api/repo/metadata_repo/_repo.py
> +        longitude = str(round(int(metadata['account'].longitude)))
```suggestion
        longitude = str(int(round(metadata['account'].longitude)))
```

2023-06-16 15:14 UTC, wasade commented on microsetta_private_api/repo/metadata_repo/tests/test_repo.py
> +                             'US:CA', 'CA', '32', '-117']],
With the corrected round, this would be 33 

```suggestion
                             'US:CA', 'CA', '33', '-117']],
```

2023-06-16 15:14 UTC, wasade commented on microsetta_private_api/repo/metadata_repo/tests/test_repo.py
> +                  '2013-10-15T09:30:00', 'US:CA', 'CA', '32', '-117']
```suggestion
                  '2013-10-15T09:30:00', 'US:CA', 'CA', '33', '-117']
```

2023-06-16 15:17 UTC, cassidysymons commented on microsetta_private_api/repo/metadata_repo/_repo.py
> +        latitude = str(round(int(metadata['account'].latitude)))
Good catch, thanks

2023-06-16 15:39 UTC, wasade commented
This good or want to wait for push to qiita-rc?

2023-06-16 16:19 UTC, sejsong commented
Pushing to qiita-rc now.

On Fri, Jun 16, 2023 at 8:40 AM Daniel McDonald ***@***.***>
wrote:

> This good or want to wait for push to qiita-rc?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/biocore/microsetta-private-api/pull/517#issuecomment-1594887420>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AARD53OUIUHKJLJNGTWPR4TXLR45TANCNFSM6AAAAAAYBUCOLM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-06-16 17:33 UTC, merged