Allow Minors to Change age_range on Source
biocore/microsetta-private-api pull request #554
Opened 2023-12-10 05:09 UTC by cassidysymons

2023-12-11 20:34 UTC, wasade requested changes

2023-12-11 20:34 UTC, wasade commented on microsetta_private_api/api/_consent.py
> +    human_consent_age_groups = ["0-6", "7-12", "13-17", "18-plus"]
Are these defined as static strings somewhere, and can those existing variables be used?

2023-12-11 20:34 UTC, wasade commented on microsetta_private_api/api/tests/test_api.py
> +    def sign_data_consent_new_age_invalid(self):
This method won't execute as a test unless prefixed with `test_`

```suggestion
    def test_sign_data_consent_new_age_invalid(self):
```

2023-12-11 20:34 UTC, wasade commented on microsetta_private_api/api/tests/test_api.py
>      def sign_biospecimen_consent(self):
...same here

Are these actually running? Historically, the unit test module only executed methods prefixed with `test` as part of the test suite

2023-12-11 20:34 UTC, wasade commented on microsetta_private_api/api/tests/test_api.py
> +    def sign_data_consent_new_age_valid(self):
same

2023-12-11 20:34 UTC, wasade commented on microsetta_private_api/repo/consent_repo.py
>          if age_range == "18-plus":
these strings are replicated a lot in the codebase...

2023-12-11 20:34 UTC, wasade commented on microsetta_private_api/repo/consent_repo.py
> +            sql = sql.format(consent_join)
Can this use SQL string composition instead (https://www.psycopg.org/docs/sql.html#module-psycopg2.sql)? Risk of injection right now is low (non-existent?) with current code, but doing it now is defensive for future change

2023-12-12 00:14 UTC, cassidysymons commented
@wasade Ready for re-review, thanks!

2023-12-12 16:31 UTC, wasade approved these changes
Thank you, @cassidysymons!

2023-12-12 16:37 UTC, merged