Scrub interested users
biocore/microsetta-private-api pull request #564
Opened 2024-02-15 17:54 UTC by ayobi

Once the account scrub is done we want to also scrub the campaign.interested_users entry as well per https://github.com/biocore/microsetta-private-api/issues/424. Currently, this uses the account email address and finds the entry in the interested_users table.

2024-02-16 00:18 UTC, cassidysymons requested changes
Along with the specific comments in the most recent commit, can you please add unit tests that exercise the relevant functions for both successful and failed outcomes to ensure that we're handling each outcome appropriately?

Also, is there any way to cleanly isolate the most recent commit and remove the commits related to the deletion queue from this branch? If not, it's not a huge deal, but it muddies the water on comparing changes to have the same things showing up on multiple PRs.

2024-02-16 00:18 UTC, cassidysymons commented on microsetta_private_api/repo/interested_user_repo.py
> +                return True
I believe that this will break the for loop that begins on line 225, meaning that only one record in `interested_users` will actually get scrubbed. Can you take a more defensive approach, such as creating an `errors` variable with a value of `False`, setting it to `True` if any records fail to update, then `return errors`?

2024-02-16 00:18 UTC, cassidysymons commented on microsetta_private_api/repo/interested_user_repo.py
> +                "SELECT * FROM campaign.interested_users WHERE email LIKE %s",
This should check email based on case-insensitive equivalency, not a LIKE match. If we're deleting john@hotmail.com from our database, this code as written would inappropriately scrub bigjohn@hotmail.com and littlejohn@hotmail.com from the `interested_users` table.

2024-02-16 00:18 UTC, cassidysymons commented on microsetta_private_api/admin/admin_impl.py
> +        interested_users_repo.scrub(acct.email)
The `interested_users_repo.scrub()` function can return False if one or more of the records fails to scrub, but its return value is ignored here. Ideally, it would raise an exception so that we don't end up with inconsistent state in the database, where the account has been scrubbed but records in `interested_users` have not.

2024-02-16 02:50 UTC, ayobi commented on microsetta_private_api/repo/interested_user_repo.py
> +                "SELECT * FROM campaign.interested_users WHERE email LIKE %s",
Bah, you're right, thanks. I'll fix that.

2024-02-16 23:28 UTC, ayobi commented on microsetta_private_api/admin/admin_impl.py
> +        interested_users_repo.scrub(acct.email)
@cassidysymons I see, at the moment I see a user can update their email address, but it doesn't look like it also updates their respective address on the interested_users table https://github.com/biocore/microsetta-interface/blob/621691c21223e1889b514c571ea7317372d94dc1/microsetta_interface/implementation.py#L1055C1-L1085C56 so there are probably users that have updated their email that wouldn't be on the table.

2024-02-17 03:11 UTC, closed without merging

2024-02-17 03:24 UTC, ayobi commented
> Along with the specific comments in the most recent commit, can you please add unit tests that exercise the relevant functions for both successful and failed outcomes to ensure that we're handling each outcome appropriately?
> 
> Also, is there any way to cleanly isolate the most recent commit and remove the commits related to the deletion queue from this branch? If not, it's not a huge deal, but it muddies the water on comparing changes to have the same things showing up on multiple PRs.

@cassidysymons I've decided to close this PR and make a new one (with most of the improvements) to make it easier for migration 👍