scrub interested users per #424
biocore/microsetta-private-api pull request #565
Opened 2024-02-17 03:12 UTC by ayobi

Once the account scrub is done we want to also scrub the campaign.interested_users entry as well per https://github.com/biocore/microsetta-private-api/issues/424. Currently, this uses the account email address and finds the entry in the interested_users table.

2024-04-02 21:27 UTC, cassidysymons requested changes

2024-04-02 21:27 UTC, cassidysymons commented on microsetta_private_api/repo/interested_user_repo.py
> +        # email = "%" + email + "%"
Can this comment be removed?

2024-04-02 21:27 UTC, cassidysymons commented on microsetta_private_api/repo/interested_user_repo.py
> +            interested_user.latitude = 0
Both latitude and longitude are nullable columns - since 0 is technically a valid value for both lat and long, it seems like setting them to null would be a bit more appropriate than 0 for a scrubbed record.

2024-04-02 21:27 UTC, cassidysymons commented on microsetta_private_api/repo/interested_user_repo.py
> +        return updated
The scrub function returns a value but `admin_impl.delete_account()` doesn't do anything with it. If any of the update operations fail, I think we'd want to throw an Exception so we don't end up in a situation where part of the scrub/delete operation succeeded and part didn't.

2024-04-03 17:55 UTC, ayobi commented on microsetta_private_api/repo/interested_user_repo.py
> +                raise RepoException("Error scrubbing interested user")
Ah yes, thank you

2024-04-03 19:39 UTC, cassidysymons commented
@ayobi Ran into one more issue while testing this on staging. The [update_interested_user](https://github.com/biocore/microsetta-private-api/blob/master/microsetta_private_api/repo/interested_user_repo.py#L54) function doesn't touch the `latitude`, `longitude`, or `confirm_consent` columns so those aren't being scrubbed. Can you add those columns to `update_interested_user` and I'll put it back up on staging for one more round of testing? Thanks.

2024-04-03 20:13 UTC, ayobi commented
Ah good catch, sorry about that, they're added now 👍

2024-04-03 21:04 UTC, cassidysymons approved these changes

2024-04-03 21:05 UTC, merged