create barcodes for existing kits
biocore/microsetta-private-api pull request #567
Opened 2024-03-08 04:17 UTC by ayobi

Taking from task description, this PR covers part 1:

Add a barcode to an existing kit (new feature). In this scenario, there already exists a kit in the database with one or more barcodes. The user will log into microsetta-admin and add barcodes to one or more kits, and it needs to provide the following options:

- Add barcodes to a single kit. The user would enter a Kit ID into a text field, then have the option to either enter a barcode to add to the kit OR dynamically generate a new barcode to add to the kit (using the existing barcode generation function). If it's a generated barcode, the output should inform the user of the newly created barcode. Otherwise, the output should be a success/failure message.

- Add barcodes to several kits. The user would upload a CSV file with Kit IDs in the first column. They would then have the option to either add a dynamically generated barcode to each kit OR put a barcode in the second column of the CSV file. In either case, the tool should return a CSV file with the Kit IDs and the newly added barcodes.

2024-03-26 00:56 UTC, ayobi commented
Added part 2:

The user can now provide their own barcode(s) if needed when they're creating a kit. This can be done either by providing the barcode(s) in the field(s) OR they can upload a list of barcodes via a csv file.

2024-06-06 16:30 UTC, cassidysymons requested changes
I suspect the UI changes in microsetta-admin combined with collapsing the two API paths into one will introduce significant changes, so let's knock those out, then I'll do another round of code review.

2024-06-06 16:30 UTC, cassidysymons commented on microsetta_private_api/api/microsetta_private_api.yaml
> +
Let's collapse these down to a single API path since they're both doing the same thing - adding barcode(s) to kit(s). Whether it's user-provided or system-generated barcodes can be a part of the request.

2024-06-06 16:30 UTC, cassidysymons commented on microsetta_private_api/repo/admin_repo.py
> +    def _generate_novel_barcodes_admin(self,
Is there a reason you added this function rather than using the `_generate_novel_barcodes` function that already exists?

2024-06-17 14:07 UTC, ayobi commented on microsetta_private_api/repo/admin_repo.py
> +    def _generate_novel_barcodes_admin(self,
`_generate_novel_barcodes` is more complex and tailored for generating barcodes tied to specific kit names, whereas `_generate_novel_barcodes_admin `is simpler and used for generating barcode(s) without associating them with kit names. I suppose I felt that separating the functions allows for more modularity, maintainability, and clarity in case things scale with this feature in the future.

2024-06-17 15:33 UTC, cassidysymons commented on microsetta_private_api/repo/admin_repo.py
> +    def _generate_novel_barcodes_admin(self,
Is there an actual use case for generating barcodes and not associating them with a Kit ID? The corresponding PR in `microsetta-admin` ends up doing precisely that, first [requesting novel barcodes](https://github.com/biocore/microsetta-admin/pull/99/files#diff-b23ea711ab49d62652d71b16d5097513712c6df215296d1803f1f56982aace04R597), then [associating them with kits](https://github.com/biocore/microsetta-admin/pull/99/files#diff-b23ea711ab49d62652d71b16d5097513712c6df215296d1803f1f56982aace04R654).

Unless there's a reason we'd ever create barcodes and not associate them with kits (which I don't believe there is), this function is creating bloat and reducing maintainability.

2024-06-17 19:37 UTC, wasade commented on microsetta_private_api/repo/admin_repo.py
> +    def _generate_novel_barcodes_admin(self,
The data model for a microsetta project shouldn't allow this given the FK between `ag_kit` and `ag_kit_barcodes`. 

The value of a kit ID outside of a microsetta project is uncertain. But, they're easy to generate and disregard (whereas generating after the fact would not be fun)

2024-06-18 20:05 UTC, ayobi commented on microsetta_private_api/repo/admin_repo.py
> +    def _generate_novel_barcodes_admin(self,
Ah, I see. Thanks 👍

2024-07-30 17:54 UTC, cassidysymons commented
@ayobi Can you please take a look at the conflict on this PR? I think you'll need to merge biocore:master into your branch to pick up new changes, and then possibly re-adjust the conflicting function. Thanks.

2024-08-01 18:24 UTC, cassidysymons requested changes

2024-08-01 18:24 UTC, cassidysymons commented on microsetta_private_api/admin/admin_impl.py
> +        barcode = admin_repo._generate_novel_barcodes(
Per the comments that Daniel and I left on the PR earlier, generating barcodes that are not associated with a kit_name shouldn't be allowed. I'm leaving this comment once, but there are changes throughout the PR that need to be adjusted (here, tests, the `_generate_novel_barcodes` function in `admin_repo.py`).

2024-08-01 18:24 UTC, cassidysymons commented on microsetta_private_api/repo/admin_repo.py
> +    def _insert_barcodes_to_existing_kit(self,
Given that there's no upstream check that the project_ids for all of the kits being updated are identical, it's unsafe to make that assumption here. The best course of action is to check the project IDs on a per-kit basis within this function.

2024-08-06 20:47 UTC, cassidysymons requested changes
Please let me know if you have any questions about isolated issues and/or this task in broad strokes. Each round of review has been a combination of steps forward and backwards and I'm concerned that it's not moving towards a polished and accurate addition to the codebase.

2024-08-06 20:47 UTC, cassidysymons commented on microsetta_private_api/repo/admin_repo.py
> +    def _insert_barcodes_to_existing_kit(self,
@ayobi Was this comment addressed? Or am I missing a reason that it's not relevant?

2024-08-06 20:47 UTC, cassidysymons commented on microsetta_private_api/admin/admin_impl.py
> +            number_of_kits, number_of_samples, kit_names)
Doesn't this essentially duplicate the existing code to create kits?

2024-08-07 00:19 UTC, ayobi commented on microsetta_private_api/repo/admin_repo.py
> +    def _insert_barcodes_to_existing_kit(self,
If I understood correctly I set the check here https://github.com/biocore/microsetta-private-api/blob/224e5fe7b64c773fbfab8f55ab2b425f6d5aeb2c/microsetta_private_api/repo/admin_repo.py#L926-L927

2024-08-07 00:21 UTC, ayobi commented on microsetta_private_api/admin/admin_impl.py
> +            number_of_kits, number_of_samples, kit_names)
Ah shoot, my apologies. Tunnel vision.

2024-08-07 00:43 UTC, cassidysymons commented on microsetta_private_api/repo/admin_repo.py
> +    def _insert_barcodes_to_existing_kit(self,
It's not working as intended from two different standpoints:

1) I have a test kit that has multiple barcodes, each of which is associated with two projects. I added a single barcode to this test kit. The newly created barcode is only associated with one of the projects, when it should be associated with both.
2) I have two test kits, call them KitA and KitB. KitA has one barcode that is associated with Project A. KitB has multiple barcodes, all of which are associated with Projects B and C. I used the Add Barcodes to Multiple Kits feature, uploaded a spreadsheet with KitA and KitB, and received a spreadsheet with newly added barcodes for both kits. However, neither of those barcodes exist in the database.

There's no practical reason to prevent admins from adding barcodes to kits from multiple projects in one transaction. Since the code to associate new barcodes with the right projects needs to be refactored, I'd suggest dropping the validation and just doing all of the project ID logic (read existing association/create new association) on a per-kit basis.

2024-08-07 17:07 UTC, ayobi commented on microsetta_private_api/admin/admin_impl.py
> +            number_of_kits, number_of_samples, kit_names)
On second look @cassidysymons, it does not. The `create_kits` function in the `admin_impl ` uses `_generate_novel_barcodes` in the `admin_repo`. https://github.com/biocore/microsetta-private-api/blob/224e5fe7b64c773fbfab8f55ab2b425f6d5aeb2c/microsetta_private_api/repo/admin_repo.py#L808-L818

This function, `generate_barcodes`, is used by `handle_barcodes` in the `admin_impl` which has its isolated use of adding barcodes to existing kits.
https://github.com/biocore/microsetta-private-api/blob/224e5fe7b64c773fbfab8f55ab2b425f6d5aeb2c/microsetta_private_api/admin/admin_impl.py#L285-L322

2024-08-07 17:20 UTC, cassidysymons commented on microsetta_private_api/admin/admin_impl.py
> +            number_of_kits, number_of_samples, kit_names)
Both functions generate novel kit names, then generate novel barcodes. The new code in `generate_barcodes` is replicating what happens in `create_kits`. Is that not duplicating code?

2024-08-07 17:28 UTC, ayobi commented on microsetta_private_api/admin/admin_impl.py
> +            number_of_kits, number_of_samples, kit_names)
Ah I see what you mean. Sorry, I thought you meant if it gets called twice resulting in duplicated kit names and barcodes.

2024-08-07 18:10 UTC, ayobi commented on microsetta_private_api/admin/admin_impl.py
> +            number_of_kits, number_of_samples, kit_names)
Would you rather me modify the `create_kits ` function accordingly to use in the `handle_barcodes` to avoid the duplication?

2024-08-19 03:21 UTC, cassidysymons requested changes

2024-08-19 03:21 UTC, cassidysymons commented on microsetta_private_api/repo/admin_repo.py
> +        user_barcodes : list of str
Given the fact that the position of barcodes in provided CSVs matters, this should be something with more structure than a list.

2024-08-27 01:21 UTC, cassidysymons requested changes
Please let me know if you have any questions about what I've flagged here.

2024-08-27 01:21 UTC, cassidysymons commented on microsetta_private_api/repo/admin_repo.py
> +                )
This feels fairly convoluted and possibly driven more by the earlier implementation than the understanding of sample slots. Given the intent of sample slots, couldn't this be simplified to something like (spitballing concepts, not actual code):
```
for i in range(number_of_samples):
    if i in range(len(user_barcodes)):
        slot[i] = user_barcodes[i]
    else:
        slot[i] = _generate_novel_barcodes()
````

There's code needed to set up the tuples at each slot, but it feels like there's a lot of room to make this code more readable and maintainable.

2024-08-27 01:21 UTC, cassidysymons commented on microsetta_private_api/repo/admin_repo.py
> +                except Exception as e:
Did you encounter any exceptions here while developing this? It seems concerning that there's an expectation of a potential error here.

2024-08-27 01:21 UTC, cassidysymons commented on microsetta_private_api/repo/admin_repo.py
> +            print("barcode projects", barcode_projects)
```suggestion
```

2024-08-27 01:21 UTC, cassidysymons commented on microsetta_private_api/repo/admin_repo.py
> +        print("create kit tuple", kit_name_and_barcode_tuples_list)
```suggestion
```

2024-08-29 22:07 UTC, ayobi commented on microsetta_private_api/admin/admin_impl.py
>          return jsonify(diag), 200
Ah yes, deleting.

2024-08-30 00:22 UTC, ayobi commented on microsetta_private_api/repo/admin_repo.py
> +        user_barcodes : list of str
Ah yes, should say list of lists of strings

2024-08-30 00:22 UTC, ayobi commented on microsetta_private_api/api/microsetta_private_api.yaml
> +      responses:
Ah yes, I'll update

2024-08-30 00:22 UTC, ayobi commented on microsetta_private_api/admin/admin_impl.py
> +        raise ValueError("The number of kit IDs must "
Ah, yes. Thanks👍

2024-08-30 00:22 UTC, ayobi commented on microsetta_private_api/admin/admin_impl.py
> +            diag = admin_repo.check_barcode_exists(barcode)
It was taking a while when I would upload a list of barcodes so I decided to create the function. Testing it again though, it's now checking quite quickly. I did reinstall my local db recently so maybe that was it. I'll switch to using `retrieve_diagnostics_by_barcode` again. 👍

2024-08-30 00:22 UTC, ayobi commented on microsetta_private_api/admin/admin_impl.py
> +        return jsonify(barcode[1])
Ah, I should add `201` there.

2024-08-30 00:22 UTC, ayobi commented on microsetta_private_api/admin/admin_impl.py
> +        else:
`generate_barcodes` is for creating kits, as you can see, it has `num_kits` and `num_samples` in the body
`generate_barcodes_multiple` is for adding barcodes to existing kits, it has just `kit_ids` in the body so I just check the length as one kit id = one barcode.
I could make it clearer in the naming of the payload to say something like `generate_barcodes_for_kits`, `generate_barcode_single_for_existing_kits`, and `generate_barcodes_multiple_for_existing_kits`?

2024-08-30 00:23 UTC, ayobi commented on microsetta_private_api/admin/admin_impl.py
> +            if body['generate_barcode_single'] == 'on':
Yeah, I don't think so, I'll just put  `if generate_barcode_single` then.

2024-08-30 00:23 UTC, ayobi commented on microsetta_private_api/admin/admin_impl.py
> +            diag = admin_repo.check_kit_id_exists(kit_id)
Ah, I didn't see that function. No issue using that instead. 👍

2024-08-30 03:44 UTC, ayobi commented on microsetta_private_api/repo/admin_repo.py
> +                except Exception as e:
No, I think that was lingering from when I was testing something. Removing.

2024-10-03 00:14 UTC, cassidysymons requested changes
Along with the noted comment, there are three issues identified through user testing:
1) When I tried to Create a Kit using barcodes that already existed, I received an error of "Error message not found in the results."
2) When I click Add Barcode to Kit in the menu, click the Add Barcode to Single Kit button, enter a valid Kit ID, and choose Generate barcode, the output displays a barcode in red, but that barcode does not exist in the database.
3) When I click Add Barcode to Kit in the menu, click the Add Barcode to Multiple Kits button, upload a list of valid Kit IDs, and choose Generate barcodes, the output displays a single barcode in red, which does not exist in the database.

2024-10-03 00:14 UTC, cassidysymons commented on microsetta_private_api/admin/sample_summary.py
> +                print("ffq complete", ffq_complete, "ffq taken", ffq_taken)
```suggestion
```

2024-10-16 06:13 UTC, closed without merging