Survey association lock change
biocore/microsetta-private-api pull request #570
Opened 2024-04-17 17:42 UTC by ayobi

Moved the point at which sample-survey associations are locked from the frontend microsetta-interface to immediately before the sample’s metadata is pushed up to Qiita on the backend.

2024-04-22 19:16 UTC, cassidysymons requested changes

2024-04-22 19:16 UTC, cassidysymons commented on microsetta_private_api/repo/qiita_repo.py
> +    def lock_sample_to_survey(self, barcodes):
In the interest of keeping function names as descriptive and obvious as possible, I'd recommend changing this to `lock_completed_surveys_to_barcodes`. The current name makes it sound like a 1:1 relationship.

2024-04-22 19:16 UTC, cassidysymons commented on microsetta_private_api/repo/qiita_repo.py
> +                        raise RepoException("Survey IDs not found for barcode")
```suggestion
```
This shouldn't be an exception. It's possible for users to claim a sample without completing any surveys, and while it's not ideal, it shouldn't be treated as an error.

2024-04-22 19:16 UTC, cassidysymons commented on microsetta_private_api/repo/qiita_repo.py
> +        self.lock_sample_to_survey(barcodes)
Looking at this code more closely, we should move this to happen after `to_push = list(barcodes - samples_in_qiita)[:1000]` as we only want to update the locks for samples actually being pushed up. Leaving it here would mean we're changing the associations for samples that are already pushed to Qiita.

2024-04-24 21:45 UTC, cassidysymons requested changes

2024-04-24 21:45 UTC, cassidysymons commented on microsetta_private_api/repo/qiita_repo.py
> +        self.lock_completed_surveys_to_barcodes(barcodes)
```suggestion
        self.lock_completed_surveys_to_barcodes(to_push)
```

Need to limit it to only the barcodes actually being pushed to Qiita.

2024-04-24 21:45 UTC, cassidysymons commented on microsetta_private_api/repo/tests/test_qiita.py
> +    def test_lock_sample_to_survey(self):
```suggestion
    def test_lock_completed_surveys_to_barcodes(self):
```

2024-04-24 21:45 UTC, cassidysymons commented on microsetta_private_api/repo/tests/test_qiita.py
> +            t.commit()
Is there a reason you're committing the transaction here? We try to avoid committing in unit tests, and when it's strictly necessary, we need to remove the record(s) from the database in the `tearDown()` function.

2024-04-24 22:45 UTC, ayobi commented on microsetta_private_api/repo/tests/test_qiita.py
> +            t.commit()
Hi @cassidysymons, since I need to submit a survey for the barcode in order to proceed with locking the barcode to the survey I am committing so that I can ensure after that there was indeed an addition to the database table. Should we maybe move out this test to someone else since it's not really testing qiita?

2024-04-24 22:55 UTC, cassidysymons requested changes

2024-04-24 22:55 UTC, cassidysymons commented on microsetta_private_api/repo/qiita_repo.py
> +        with Transaction() as t:
```suggestion
        with self._transaction as t:
```

2024-04-24 22:55 UTC, cassidysymons commented on microsetta_private_api/repo/qiita_repo.py
> +            t.commit()
```suggestion
```

2024-04-24 22:55 UTC, cassidysymons commented on microsetta_private_api/repo/qiita_repo.py
> +from microsetta_private_api.repo.transaction import Transaction
```suggestion
```

2024-04-24 22:55 UTC, cassidysymons commented on microsetta_private_api/repo/tests/test_qiita.py
> +            t.commit()
Sorry, I wasn't considering that you were opening a new transaction in the lock function. It's considerably cleaner to keep everything in one transaction since there's no need to worry about a race condition occurring. With everything now using a single transaction, you can run the entire test using one transaction as well.

2024-04-25 01:26 UTC, ayobi commented on microsetta_private_api/repo/tests/test_qiita.py
> +            t.commit()
With those changes suggested I get `psycopg2.pool.PoolError: trying to put unkeyed connection`

2024-04-25 01:52 UTC, cassidysymons commented on microsetta_private_api/repo/tests/test_qiita.py
> +            t.commit()
Can you push the code up as it stands now so I can see it in context?

2024-04-25 02:02 UTC, ayobi commented on microsetta_private_api/repo/tests/test_qiita.py
> +            t.commit()
Pushed it up 👍

2024-04-25 02:10 UTC, cassidysymons requested changes

2024-04-25 02:10 UTC, cassidysymons commented on microsetta_private_api/repo/tests/test_qiita.py
> +            t.commit()
```suggestion
```

2024-04-25 20:25 UTC, cassidysymons commented on microsetta_private_api/repo/tests/test_qiita.py
> +            t.commit()
Any luck debugging the issue this morning?

2024-04-25 21:21 UTC, ayobi commented on microsetta_private_api/repo/tests/test_qiita.py
> +            t.commit()
No luck as of yet

2024-04-25 22:15 UTC, cassidysymons commented on microsetta_private_api/repo/qiita_repo.py
> +            sar_repo = SurveyAnswersRepo(t)
```suggestion
        admin_repo = AdminRepo(self._transaction)
        sar_repo = SurveyAnswersRepo(self._transaction)
```

Fixed the indenting on the rest of the function accordingly and it should work.

2024-04-26 02:11 UTC, ayobi commented on microsetta_private_api/repo/qiita_repo.py
> +            sar_repo = SurveyAnswersRepo(t)
That did it, thank you

2024-10-02 22:51 UTC, cassidysymons commented on microsetta_private_api/tasks.py
> +            t.commit()
```suggestion
        t.commit()
```

2024-10-02 22:56 UTC, merged