vocab for samples issues
biocore/microsetta-private-api pull request #574
Opened 2024-05-13 23:56 UTC by ayobi

Adding a fixed vocabulary of potential sample issues to the Scan Barcode tool.

2024-06-03 20:49 UTC, cassidysymons requested changes

2024-06-03 20:49 UTC, cassidysymons commented on microsetta_private_api/db/patches/0139.sql
> +CREATE TABLE observation_categories (
```suggestion
CREATE TABLE sample_observation_categories (
```

Adding "sample_" as a prefix to these table names will help make their purpose abundantly clear to anyone jumping in later.

2024-06-03 20:49 UTC, cassidysymons commented on microsetta_private_api/db/patches/0139.sql
> +    categories VARCHAR(255) PRIMARY KEY
```suggestion
    category VARCHAR(255) PRIMARY KEY
```

Prefer to keep column names in the same singular/plural form as the data they're storing.

2024-06-03 20:49 UTC, cassidysymons commented on microsetta_private_api/db/patches/0139.sql
> +INSERT INTO observation_categories (categories) VALUES ('Sample'), ('Swab'), ('Tube');
```suggestion
INSERT INTO sample_observation_categories (category) VALUES ('Sample'), ('Swab'), ('Tube');
```

2024-06-03 20:49 UTC, cassidysymons commented on microsetta_private_api/db/patches/0139.sql
> +CREATE TABLE observation_errors (
```suggestion
CREATE TABLE sample_observations (
```

Some of these conditions are not errors in a strict sense, so it would be more appropriate to name the table "sample_observations."

2024-06-03 20:49 UTC, cassidysymons commented on microsetta_private_api/db/patches/0139.sql
> +    error VARCHAR(255),
```suggestion
    category VARCHAR(255) NOT NULL,
    observation VARCHAR(255) NOT NULL,
```

Along with the column name change and enforcing `NOT NULL` constraints, want a couple of keys on this table:
1) A primary key, either an int or UUID (e.g. `observation_id UUID PRIMARY KEY DEFAULT uuid_generate_v4()`)
2) A unique key on the combination of category+observation to ensure we don't end up with duplicate values down the line.

2024-06-03 20:49 UTC, cassidysymons commented on microsetta_private_api/db/patches/0139.sql
> +    project_id INT,
A couple of things here:
1) The API currently isn't respecting the association between an observation and a project ID. I pulled up the code on our staging server and I'm getting the observations created below for barcodes associated with any project, not just 118.
2) Let's move this association to a separate table (e.g. `sample_observation_project_associations`). A given observation can (and likely will) be used for multiple projects, so we don't want to duplicate all of the data.

2024-06-03 20:49 UTC, cassidysymons commented on microsetta_private_api/db/patches/0139.sql
> +ALTER TABLE barcodes.barcode_scans ADD COLUMN observations VARCHAR(255);
I think it makes more sense to have a separate table to store the association between a scan and the observations that were recorded as part of that scan. One of the forward-looking use cases we have for this data is analyzing the frequency with which they occur, and querying a table for that specifically will be more efficient than clunky `LIKE` statements on a string column in the `barcode_scans` table.

2024-06-03 20:49 UTC, cassidysymons commented on microsetta_private_api/admin/tests/test_admin_repo.py
> +            "observations": None
It looks like there aren't any new unit tests that exercise the observations functionality being added. Off the top of my head, there are a few scenarios that would be valuable to test:
1) When no observations are recorded for a scan, confirm that the database does not reflect any observations.
2) When one or more observations are recorded for a scan, confirm that the database reflects all of the observations.
3) When a scan attempts to record observations that are not associated with the barcode's project(s), confirm that it raises a RepoException.

2024-06-03 20:49 UTC, cassidysymons commented on microsetta_private_api/admin/tests/test_admin_repo.py
> +                print(diag['scans_info'][0], first_scan)
```suggestion
```

Let's make sure to pull out debug info when PRs are ready to review.

2024-06-06 20:59 UTC, cassidysymons requested changes

2024-06-06 20:59 UTC, cassidysymons commented on microsetta_private_api/db/patches/0140.sql
> +    project_id INT NOT NULL,
`project_id` should also be a foreign key referencing `barcodes.project.project_id`

2024-06-06 20:59 UTC, cassidysymons commented on microsetta_private_api/db/patches/0140.sql
> +CREATE TABLE sample_observation_categories (
```suggestion
CREATE TABLE barcodes.sample_observation_categories (
```

Apologies for missing this the first time around, but let's make sure to specify a schema when creating tables (this applies to this and all following queries, don't want to needlessly replicate the comment). Ideally, we want all new queries (whether in DB patches or repos) to specify the schema as well. Some legacy code doesn't, and queries work without it, but specificity helps prevent issues down the road.

2024-06-06 20:59 UTC, cassidysymons commented on microsetta_private_api/repo/admin_repo.py
> +                    )
Given that there's not a unique constraint on `observation` (and we don't want there to be), this isn't a safe approach. The UI in `microsetta-admin` should directly pass the `observation_id` into the API.

2024-06-06 20:59 UTC, cassidysymons commented on microsetta_private_api/repo/admin_repo.py
> +            cur.execute("""
I don't think it's appropriate to return every possible observation in `retrieve_diagnostics_by_barcode` function. There are a handful of points in the codebase that call `retrieve_diagnostics_by_barcode` and most of them are only looking for info about the barcode, so it's creating bloat.

Instead, let's create a new API path to serve this purpose. The input would be a list of one or more project IDs and the output would be the possible observations that can be rendered for those project IDs.

2024-06-06 20:59 UTC, cassidysymons commented on microsetta_private_api/repo/admin_repo.py
> +                scan_info['technician_notes'],
Is this code change necessary or is it a residual effect of moving the observations for a given scan into a separate table?

2024-06-06 20:59 UTC, cassidysymons commented on microsetta_private_api/repo/admin_repo.py
> +                    cur.execute(
Before inserting the observations into `sample_barcode_scan_observations`, it would be valuable to verify that they're associated with the barcode(s) project(s). The UI _shouldn't_ allow invalid observations to be used, but validating would be more defensive.

2024-06-13 00:26 UTC, ayobi commented on microsetta_private_api/repo/admin_repo.py
> +                scan_info['technician_notes'],
Yeah, residual, removing

2024-06-18 00:36 UTC, cassidysymons requested changes

2024-06-18 00:36 UTC, cassidysymons commented on microsetta_private_api/db/patches/0140.sql
> +    UNIQUE (observation_id)
```suggestion
    UNIQUE (observation_id, project_id)
```

2024-06-18 00:36 UTC, cassidysymons commented on microsetta_private_api/db/patches/0140.sql
> +    UNIQUE (observation_id)
We need to be able to associate observations with more than one project.

2024-06-18 00:36 UTC, cassidysymons commented on microsetta_private_api/repo/admin_repo.py
> +            return [dict(x) for x in rows]
Since multiple functions in admin_repo are now using this helper function, let's move it from being an inner function with multiple instances to a single top-level function.

2024-06-18 00:36 UTC, cassidysymons commented on microsetta_private_api/repo/admin_repo.py
> +            return observations
This code does not work as intended when a sample is associated with multiple projects and two or more of the projects are associated with the same observation. It shows multiple copies of the same observation on the `microsetta-admin` UI.

2024-06-18 00:36 UTC, cassidysymons commented on microsetta_private_api/admin/admin_impl.py
> +        t.commit()
Given that this API path is read-only, is there a reason to have a `commit` here?

2024-06-18 00:36 UTC, cassidysymons commented on microsetta_private_api/admin/admin_impl.py
> +    response.status_code = 201
Is there a reason you're returning `201` rather than `200` here?

2024-06-24 23:15 UTC, ayobi commented on microsetta_private_api/admin/admin_impl.py
> +        t.commit()
You're right, I can't remember what I was doing when I was trying to get it to work

2024-06-24 23:15 UTC, ayobi commented on microsetta_private_api/admin/admin_impl.py
> +    response.status_code = 201
My mistake, changed.

2024-06-24 23:16 UTC, ayobi commented on microsetta_private_api/admin/admin_impl.py
> +        return response
You're right, it isn't necessary, thank you for the catch.

2024-06-24 23:28 UTC, ayobi commented on microsetta_private_api/repo/admin_repo.py
> +            return observations
Should be fixed now

2024-07-05 17:56 UTC, cassidysymons commented
@ayobi Can you please merge biocore:master into ayobi:vocab_samples_issues? There's a database patch missing that causes the patching process to fail. Thanks.

2024-07-05 17:59 UTC, ayobi commented
@cassidysymons merged 🎉

2024-07-09 18:16 UTC, cassidysymons requested changes
Two minor adjustments, then this should be good to merge. Thanks!

2024-07-09 18:16 UTC, cassidysymons commented on microsetta_private_api/admin/tests/test_admin_repo.py
> +            "category": None
```suggestion
            "observations": None
```

Tests should reflect exactly what microsetta-admin is posting to microsetta-private-api.

2024-07-09 18:16 UTC, cassidysymons commented on microsetta_private_api/admin/tests/test_admin_repo.py
> +            "category": None
```suggestion
            "observations": None
```

Tests should reflect exactly what microsetta-admin is posting to microsetta-private-api.

2024-07-30 17:50 UTC, merged