Multi ffqs fix
biocore/microsetta-private-api pull request #581
Opened 2024-08-31 01:23 UTC by ayobi

2024-09-16 17:08 UTC, cassidysymons requested changes

2024-09-16 17:08 UTC, cassidysymons commented on microsetta_private_api/admin/sample_summary.py
> +                    ffq_taken = False
Given the change from sample to source, I think it makes sense to move this code block into the if statement on Line 51 (`if source is not None and source_type == Source.SOURCE_TYPE_HUMAN`). Additionally, it makes sense to harmonize what they're doing. For example, `get_ffq_status_by_source` could return `True, True` but `vio_id` could be None.

I'd suggest first looking for a match including `sample_id` since a good chunk of historical data will include that. Failing an exact match with `sample_id` you can fall back to a match on source.

2024-09-16 17:08 UTC, cassidysymons commented on microsetta_private_api/repo/vioscreen_repo.py
> +            print("Upserted rows:", rows)
Was this exploratory/debug code that was intended to be removed prior to committing?

2024-09-16 17:45 UTC, ayobi commented on microsetta_private_api/repo/vioscreen_repo.py
> +            print("Upserted rows:", rows)
Ah yes, meant to remove that

2024-09-16 19:43 UTC, ayobi commented on microsetta_private_api/admin/sample_summary.py
> +                    ffq_taken = False
So you're saying it'd be better to change `if source is not None and source_type == Source.SOURCE_TYPE_HUMAN` to first check for a `sample_id` match then fall back on source? Something like this on line 51:
``` python 
if sample is not None:
    vio_id = template_repo.get_vioscreen_id_if_exists(account.id,
                                                      source.id,
                                                      sample.id)
    if not vio_id:
        vio_id = template_repo.get_vioscreen_id_if_exists(account.id,
                                                          source.id,
                                                          None)
else:
    if source is not None and source_type == Source.SOURCE_TYPE_HUMAN:
        vio_id = template_repo.get_vioscreen_id_if_exists(account.id,
                                                          source.id,
                                                          None)
    if source:
        ffq_complete, ffq_taken, _ = vs_repo.get_ffq_status_by_source(source.id)
    else:
        ffq_complete = False
        ffq_taken = False
```

2024-09-16 21:50 UTC, cassidysymons requested changes

2024-09-16 21:50 UTC, cassidysymons commented on microsetta_private_api/repo/vioscreen_repo.py
> +                return results
Doesn't changing the return value from a tuple to a list of tuples will break the code that uses this function? The unit tests work fine because they test the function in isolation, but is this still working when you try to run a sample summary report through microsetta-admin?

2024-09-16 21:50 UTC, cassidysymons commented on microsetta_private_api/admin/sample_summary.py
> +                        vs_repo.get_ffq_status_by_source(source.id)
Two comments here:
1) These lines are within a block of code that already checked `if source is not None` - isn't checking `if source` here redundant?
2) If we successfully obtain a `vio_id` we should check the taken/complete status of that particular `vio_id` rather than anything associated with the source.

2024-09-16 22:57 UTC, ayobi commented on microsetta_private_api/repo/vioscreen_repo.py
> +                return results
That's true, it does break. So, if the user has taken multiple FFQs for a particular sample, we'd probably need to change the columns for ffq-taken and ffq-complete to indicate which ffq they've taken and if that one was taken/complete?

2024-09-17 15:30 UTC, cassidysymons commented on microsetta_private_api/repo/vioscreen_repo.py
> +                return results
I think that's overkill for the sake of this particular function. If a sample (or source) is associated with more than one FFQ, let's return the one (and it's taken/complete statuses) that's temporally nearest to the sample collection date.

2024-09-17 20:12 UTC, ayobi commented on microsetta_private_api/repo/vioscreen_repo.py
> +                return results
Ok, in my latest commit I get the closest sample collection data in `sample_date` and `sample_time` in `ag.ag_kit_barcode` to compare in `startdate` in `ag.vioscreen_sessions`.

2024-09-17 20:12 UTC, ayobi commented on microsetta_private_api/admin/sample_summary.py
> +                        vs_repo.get_ffq_status_by_source(source.id)
Gotcha. In my latest commit I've changed it in favor of looking up FFQs status via `vio_id`. In the query though, since `vio_id` is not in `ag.ag_kit_barcode` I first use the `vio_id` to obtain the `source_id` from `ag.vioscreen_registry`. Not sure if that's the best approach.

2024-10-24 19:34 UTC, merged