Sample summary report expansion
biocore/microsetta-private-api pull request #585
Opened 2024-10-03 02:35 UTC by ayobi

At the moment, to get a sample summary report, 2 of the 3 ways we do this is by searching for a single barcode or searching through a csv file of barcodes. With this expansion, we are also going to be able to search via Kit ID, Email, Outbound Tracking Number, and Inbound Tracking Number and also see these fields in the output of the report.

2024-10-03 19:57 UTC, cassidysymons requested changes
Please let me know if you have any questions about the feedback provided. I'm a bit surprised at some of the logic reflected in the code and it would be helpful to understand the choices.

2024-10-03 19:57 UTC, cassidysymons commented on microsetta_private_api/admin/admin_impl.py
> +        project_id = None
Since all but one condition set `project_id = None`, it would be more efficient to move that statement to above the `if` block and only change it for the `project_id` condition.

2024-10-03 19:57 UTC, cassidysymons commented on microsetta_private_api/admin/sample_summary.py
> +        raise ValueError("kit_id must be defined.")
It would be helpful for the API layer to catch these `ValueErrors` and return a useful error to `microsetta-admin`

2024-10-03 19:57 UTC, cassidysymons commented on microsetta_private_api/admin/sample_summary.py
> +
Many of these values are already being exposed here from `admin_repo.get_diagnostics_by_barcode()` - is there a reason you're re-retrieving them?

2024-10-03 19:57 UTC, cassidysymons commented on microsetta_private_api/repo/admin_repo.py
> +            cur.execute(query_barcodes, [tuple(ag_kit_ids)])
Is there a reason this can't be done in one query using a join statement?

2024-10-03 19:57 UTC, cassidysymons commented on microsetta_private_api/repo/admin_repo.py
> +            SELECT created_with_kit_id
This will not work as intended. `created_with_kit_id` is only populated if the account was created using a Kit ID, which is only a subset of historical accounts and is impossible for newer accounts. You need to leverage the account->source->sample relationship to find samples by email.

2024-10-03 19:57 UTC, cassidysymons commented on microsetta_private_api/repo/admin_repo.py
> +            cur.execute(query_barcodes, [tuple(kit_ids)])
Is there a reason this isn't done as one query using a join statement?

2024-10-03 19:57 UTC, cassidysymons commented on microsetta_private_api/repo/admin_repo.py
> +            cur.execute(query_barcodes, [tuple(kit_ids)])
Is there a reason this isn't done as one query using a join statement?

2024-10-03 19:57 UTC, cassidysymons commented on microsetta_private_api/repo/kit_repo.py
> +    def get_kit_id_name_by_barcode(self, barcode):
Is there a reason you're not leveraging [existing code](https://github.com/biocore/microsetta-private-api/blob/master/microsetta_private_api/repo/sample_repo.py#L399) that does this?

2024-10-22 17:48 UTC, cassidysymons commented on microsetta_private_api/repo/admin_repo.py
> +            WHERE s.participant_email IN %s
`participant_email` is a legacy field that's no longer collected. This needs to use the `email` column in the `ag.account` table.

2024-10-22 19:54 UTC, cassidysymons requested changes

2024-10-22 19:54 UTC, cassidysymons commented on microsetta_private_api/admin/sample_summary.py
> +
A sample's [full scan history](https://github.com/biocore/microsetta-private-api/blob/master/microsetta_private_api/repo/admin_repo.py#L454) is part of the information returned from `AdminRepo.retrieve_diagnostics_by_barcode()`. There's no reason to re-retrieve that information.

2024-10-22 19:54 UTC, cassidysymons commented on microsetta_private_api/admin/sample_summary.py
> +                admin_repo.get_inbound_tracking_by_barcodes(barcode)
Three separate helper functions to each grab one piece of information about a kit seems inefficient. `KitRepo` doesn't really serve the purpose we need since it's oriented around `ag.ag_kit` and `ag.ag_kit_barcodes`. I'd suggest creating a new function in `AdminRepo` named `get_kit_by_barcode()` that retrieves all of the output we need for this report.

2024-10-22 19:54 UTC, cassidysymons commented on microsetta_private_api/repo/admin_repo.py
> +    def get_barcodes_filter(self, kit_ids=None, emails=None,
Any time we add a new function to a repo, there should be corresponding unit tests to exercise the functionality and establish in an automated fashion that it's working as intended. Please add unit tests that fully exercise the various parameters for `get_barcodes_filter()`.

2024-10-24 20:56 UTC, cassidysymons commented on microsetta_private_api/admin/sample_summary.py
> +        vs_repo = VioscreenRepo(t)
@ayobi Is this new change introduced during conflict resolution intentional?

2024-10-24 21:12 UTC, ayobi commented on microsetta_private_api/admin/sample_summary.py
> +        vs_repo = VioscreenRepo(t)
No, fixing, sorry about that.

2024-10-28 16:18 UTC, cassidysymons requested changes

2024-10-28 16:18 UTC, cassidysymons commented on microsetta_private_api/admin/admin_impl.py
> +        (body["inbound_tracking_numbers"])
Searching by either inbound or outbound tracking number generates the following exception:
```
[2024-10-28 09:03:38 -0700] [4033] [ERROR] Exception on /api/admin/account_barcode_summary [POST]
Traceback (most recent call last):
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/connexion/decorators/security.py", line 327, in wrapper
    return function(request)
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/connexion/decorators/uri_parsing.py", line 144, in wrapper
    response = function(request)
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/connexion/decorators/validation.py", line 184, in wrapper
    response = function(request)
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/connexion/decorators/validation.py", line 384, in wrapper
    return function(request)
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/connexion/decorators/response.py", line 103, in wrapper
    response = function(request)
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/connexion/decorators/parameter.py", line 121, in wrapper
    return function(**kwargs)
  File "/Users/api_user/microsetta-private-api-sample_summary_report_expansion/microsetta_private_api/admin/admin_impl.py", line 528, in query_barcode_stats
    if len(barcodes) > 1000:
TypeError: object of type 'function' has no len()
```

2024-10-28 19:06 UTC, ayobi commented on microsetta_private_api/admin/admin_impl.py
> +        (body["inbound_tracking_numbers"])
Thanks for catching this @cassidysymons, I incorrectly formatted `get_barcodes_by_outbound_tracking_numbers(body["outbound_tracking_numbers"])` `get_barcodes_by_inbound_tracking_numbers(body["inbound_tracking_numbers"])`

2024-10-29 00:22 UTC, merged